set(SDK_PATH "/home/xwx/xinkeshipei/TuyaOpen/platform/SiWx917/sdks/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.1")
set(PKG_PATH "/home/xwx/.silabs/slt/installs")

add_library(slc_tuyaopen_weather_get_demo OBJECT
    "${SDK_PATH}/../wiseconnect/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/malloc_thread_safety.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/GSPI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/SAI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/SPI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/aux_reference_volt_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_adc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_dac.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_gpdma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_gspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_i2s.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_opamp.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_qspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_spi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/src/sl_si91x_clock_manager.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_bod.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/rsi_d_cache.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_adc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_bjt_temperature_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_dma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_gspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_i2c.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_i2s.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_psram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_psram_handle.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_ssi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_ulp_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_i2c.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/hal/src/sl_si91x_hal_soc_soft_reset.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gap_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gatt_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_ble.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_common_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_common_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_utils.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/sl_si91x_ble.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/crypto_utility/src/sl_si91x_crypto_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/gcm/src/sl_si91x_gcm.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/wrap/src/sl_si91x_wrap.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sli_net_si91x_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sli_wifi_memory_manager.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sli_wifi_power_profile.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_basic_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sli_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_for_lwip.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sli_net_common_utility.c"
    "${SDK_PATH}/../wiseconnect/components/sli_si91x_wifi_event_handler/src/sli_si91x_wifi_event_handler.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/src/sli_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/src/sli_wifi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi_command_engine/src/sli_wifi_command_engine.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_cmsis_os2_common.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/service/sl_main/src/rtos/main_retarget.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_init.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_init_memory.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_kernel.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "../autogen/sl_event_handler.c"
    "../main.c"
)

target_include_directories(slc_tuyaopen_weather_get_demo PUBLIC
   "../config"
   "../autogen"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/board/silabs/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/crypto_utility/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/gcm/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/hal/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc/mqtt/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/wrap/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/inc"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi_command_engine/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wiseconnect/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/sl_main/inc"
    "${SDK_PATH}/platform/service/sl_main/src"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_tuyaopen_weather_get_demo PUBLIC
    "SLI_SI91X_ENABLE_IPV6=1"
    "SLI_SI91X_MCU_MOV_ROM_API_TO_FLASH=1"
    "SUPPORT_CPLUSPLUS=1"
    "SLI_SI91X_MCU_COMMON_FLASH_MODE=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1"
    "SLI_SI91X_MCU_EXTERNAL_LDO_FOR_PSRAM=1"
    "SL_BOARD_NAME=\"BRD4002A\""
    "SL_BOARD_REV=\"A07\""
    "LFS_THREADSAFE=1"
    "SLI_SI91X_LWIP_HOSTED_NETWORK_STACK=1"
    "SL_TUYAOPEN_BSS_SEGMENT_IN_PSRAM=1"
    "SIWG917M111MGTBA=1"
    "SLI_SI917=1"
    "SLI_SI917B0=1"
    "SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1"
    "SLI_SI91X_ENABLE_BLE=1"
    "SL_SI91X_ENABLE_LITTLE_ENDIAN=1"
    "BSS_SEGMENT_IN_PSRAM=1"
    "SLI_SI91X_MCU_ENABLE_RAM_BASED_EXECUTION=1"
    "__FREERTOS_OS_WISECONNECT=1"
    "I2S_INSTANCE_CONFIG=1"
    "SL_NET_COMPONENT_INCLUDED=1"
    "__STATIC_INLINE=static inline"
    "SLI_SI91X_MCU_PSRAM_APS6404L_SQH=1"
    "SLI_SI91X_MCU_PSRAM_PRESENT=1"
    "SL_SI91X_REQUIRES_INTF_PLL=1"
    "CLOCK_ROMDRIVER_PRESENT=1"
    "ULPSS_CLOCK_ROMDRIVER_PRESENT=1"
    "SL_SI91X_BOARD_INIT=1"
    "SRAM_BASE=0x0cUL"
    "SRAM_SIZE=0x4fc00UL"
    "SLI_CODE_CLASSIFICATION_DISABLE=1"
    "SLI_SI91X_MCU_ENABLE_IPMU_APIS=1"
    "SL_SI91X_SOC_MODE=1"
    "CRC_ROMDRIVER_PRESENT=1"
    "SL_SI91X_D_CACHE_ENABLE=1"
    "GPDMA_ROMDRIVER_PRESENT=1"
    "QSPI_ROMDRIVER_PRESENT=1"
    "SPI_MULTI_SLAVE=1"
    "TIMER_ROMDRIVER_PRESENT=1"
    "SL_SI91X_SI917_RAM_MEM_CONFIG=3"
    "UDMA_ROMDRIVER_PRESENT=1"
    "GSPI_CONFIG=1"
    "GSPI_MULTI_SLAVE=1"
    "SL_SI91X_GSPI_DMA=1"
    "SL_SI91X_I2C_DMA=1"
    "SL_SI91X_I2S=1"
    "SI917=1"
    "SLI_SI91X_ENABLE_OS=1"
    "SLI_SI91X_MCU_INTERFACE=1"
    "TA_DEEP_SLEEP_COMMON_FLASH=1"
    "SL_SI91X_SSI_DMA=1"
    "SSI_CONFIG=1"
    "SSI_DUAL_QUAD_COMPONENT=1"
    "SSI_INSTANCE_CONFIG=1"
    "SL_ULP_TIMER=1"
    "SL_SI91X_DMA=1"
    "SL_SI91X_ULP_UART=1"
    "SL_SI91X_USART_DMA=1"
    "ULP_UART_MODULE=1"
    "SI91X_PLATFORM=1"
    "SI91X_SYSRTC_PRESENT=1"
    "SL_SLEEP_TIMER=1"
    "__WEAK=__attribute__((weak))"
    "PLL_ROMDRIVER_PRESENT=1"
    "TEXT_SEGMENT_IN_PSRAM=1"
    "SL_WIFI_COMPONENT_INCLUDED=1"
    "configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_FREERTOS_KERNEL=freertos_kernel"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
)

target_link_libraries(slc_tuyaopen_weather_get_demo PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "c"
    "m"
    "stdc++"
    "-Wl,--end-group"
)
target_compile_options(slc_tuyaopen_weather_get_demo PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-Wall -Werror>"
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mfp16-format=ieee>
    $<$<COMPILE_LANGUAGE:C>:-Wno-missing-field-initializers>
    $<$<COMPILE_LANGUAGE:C>:-Wno-error=deprecated-declarations>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-Wall -Werror -Wno-error=deprecated-declarations>"
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Wall -Werror>"
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mfp16-format=ieee>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-missing-field-initializers>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-error=deprecated-declarations>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Wall -Werror -Wno-error=deprecated-declarations>"
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc_tuyaopen_weather_get_demo PROPERTY C_STANDARD 17)
set_property(TARGET slc_tuyaopen_weather_get_demo PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_tuyaopen_weather_get_demo PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_tuyaopen_weather_get_demo INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_psram_SoC.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:tuyaopen_weather_get_demo>/tuyaopen_weather_get_demo.map"
    "SHELL:-u _printf_float"
    -Wl,--wrap=main
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQ1z3Lix7V9xqW69Sm6soSTLXtvPTkoryc7cWJaikXaTF91icUjMDCNySPPDkpLa//4A8GMIEiQBEiCgzW5iW5ohu89pNIAG0AD+vXd1ffk/56c35vXl5c3e+71/3+1dn385uZn/dG5Wv7rbe3+3N5vd7f2y97J8Z3F5e316voCvffjTo++9+A6i2A22H+/2DmcHd3svwNYOHHe7hh/c3nzaf3u396c/3m0/hFHwT2AnL+Ar2/i9HzjAg09skiR8bxgPDw+z2PWsZTyzA9+IY2ORpI4bzIAdRAAKhW+HIEqeFjb8F76XS7vbg6JfvPiwCjwHRC+2lo++tIPtyl3n36FvXQ8U38WeGbvvDh/N1AvN1IoSM3t6toFa0siFj6DH3xubwAfG48Oj8ehu70G8cUPgGjfpk3UZgq1hhWFsJPA30/aC1DEegJVsQGSuQWI6wA+M2TJ1PceIPdvIFBhdmg1WqL4fbJUirgFoA/7grlwzAmvoGKaznBJxq+Y2qFssbmWlXmJ+t7wUxJPgpKttA+lb7taME1QGiRXfT2nQdtVUsJ8iAK5vLhenEyFs6uuuTA+RFU5fg2pauyGu49CdHmJNKxNENc0RXXk3YPcoNt2tm6AfDqaH3Ka+G3Qcu2YYub4VPU0Pma6cB7Aa7+jE0A8/hiHH1lFmcZp6PtDqrN6Bop8CijGU+jodAC9wddbvxNHfOCppElkBOr41PUBSaRtANECZEltNX6vdPADCxPWhvCkNR9PaU4USy76HP/9rUit26O6GG8aR5ZtWGL85PjiGH37bTA+7EwMV/vXNuXkGvrs2MN8d/iAfalNfm1WXgRU5Ofw0shI4bJvEki16e2EmUeBNC7DQSIUWutP1NqSuNkutQzfIwE9iJlIdS92d0mSdqjOwH4xs8oo2kWWlSbAG28pMFvH1DGpCbVgCyidq1Gd2ZBca4Y/S6OZAjR0io6G6LJsq4WZRZSMlKGNrS52JKSDTVLa6EQyzJsbWUNmFbarws4aPLdr0kNYIfZLXhkVwOvMc6SBb9bb2lKeBHwZbsE2mKOOmwvZIM3/KtK3E8oKJSpiqtg0j+I4e3FhbxwPRNPgaKtmwyW8MaSqp2ODDs3yBwwWxdFx1df390IOLh/ZbYCevzNi5N49nB2ith94tlQ4TE90S8YyDg8PK940nsuUg4gnKM7BvrT3SeMi308YjFMwRoDzVfA7an/pcExvq86gPNh51ry5u4dA9WLe+QH/FCZJ2HdlLFS+L0AzNU5wAP2+pcWjOVw1Cz0pWQeQbC/fnR/i6AZ0hNiruYewK38jK2MgK0sBlZcDCMJCtDWRIA9rIKMkbJSejFarBStYN/RSOkNxYT4IEvHZStVCJ92ui/cvMiUGqt0kdTZsJSApoDSoNteFQh8NEArl2GJsoDlmlW1s9DQogZiIOACGe8jHjQBMqDUh0Mp1Vp97Wbrta8ppJQBQFvIGPYFNAvAYBhak8l1YMzOQp5B7YSEBPYmGC78DYVBf4JBbm2mTbYT6UUk+hiWdQ66YFjxogZiJEBKIHlQYkJjLwjUyFehIEFFbwulQKAgoreCuO4UBLC/A7KDyVWSf/D2lLhp0kiEhTOYc6GjYK2WqkJjW4joaDgv891AV/DoU7OOz6qjELAlsKtrkC5gizXE8IFIY5mFhmSxLO+FC7e9Kkffk4WKJsYOiVtmdFQN1IJDMNHh32AZTqekT+sxiLo+Z3C7mjHJMgctHUYbm8o8zc2SJbPvRrRzfIMSnReRoPTacQTroFUgtTxoLUgFM7Mhq11iJs/6I2Dx25aP8C09SvH7uxmb3AVrdOLxbzBesk8FmXYMrz863tpQ590ppa7pkCtNakKJjObW1UDWlgGxkZNiPnZDSgMs/75m9+8qx48yw4lkh5Kc6PTp8FwRwnL73FyfxZ0MtxctO7eib0rgbRu12cXN88C4IlUjmrMOwxxmdkagWRFNViBRiGcOKzTq78udNfn0F3yNjzEUx06gk6W3sCtU4NfGcjTqLWyNnZff327OJEG9gFGBbcWnUjPV1Fw7t1acxzLIzerQ1q5h4IO5QusAswzN6tDfACDdc4uzEsTbfuygUOSm4RPAFF5lKrtFuFIznXVyJjmxQnk8OzLEF9eVUAsieImLZlb7QiVYPFV1KWoyTNpbeAclx8ZJb/TMwE+CGIrCSNgBmDbRzwJsZOw68dKh9lx7e05Jfj4iSTjRXQDhg9SZH4+MihPf5asiqA8dFxj/RsOHJcvGSUpNUykOnMp23dwq0lmRwXHxm0Bxxvv9WSEoGOk1hsRYmepApkEyaa1gJOhQPkqlmIjIAS2YhQWFteFYDcobBGpGqw+ENhjbjUcQkJhXXk1w6VPxTWkV+Oa3gorCUpEh8rOX1pDSRUCaH14kMC44/tdWST4+KP7fUkw76ZgoihdSST4xoa2+tIiUA3JLbXklSBTGKyZhT4XEllXLvRkHDbu1dapXcEy6CzCos5gMYvRUqb2jYqEd/GIvQOUN2pt3ABXF168dY6VBxOtrApcbFveLHse3erJBW2g0sFFV99UdqutlUXvi1I2CtXaax06NxWWwpcXGxWrtI5mxYuOSouJmHwAEcBsfVdx8IhwfHxetCxhHJUXEy+KR5rtVD5xjPSKl6KtGuXK6i4mCTW0gPm9eLwEf6nIacGvgHslG25ZOLGtwWzfFf1+KuNE9fIq3gr1TNoS3ljtuIlfMp+qGUB1eHxcfPCOEYDJh2JVbFJHCZDu7nhBkRWMfdI37M1bn+j4vSeJscyY4knwcdKH80IrEAEtjYwvwdeonCjZg+3TqxMbG0vsO/NNHSsRGmeWQvBOjz202AiXX0xR8a+8mnpyiRHxswEqM616uACuPKs0BvZ5IiebEps7GwUJ4x1keFJGUMvKE6w6qDCk2KFng9Cyw815VJiY2bzTV8f+8brY/pS4WbyFEeJrl3MDhwzHzyY07UB2IFj5pPq282kvL0MMY7Tl1MVIjs31TmWXaQUZFkW4y6Fg26KRYrBN0+eW/soSz9unVj5R4T6EazD4xoR6kengoxrRKgnkxwZ54hQTy78S/nKl/E72PAv5atOM+wiw7v8hdRakZWoTUruagIIgOy8lCYodPHhS1JQnqDQ1Q5wJykozmjt4MKT01rMV+jKhC/9LZut0JNLiY09zUptgkUHF94ki29A104mR8Y3u6UpFd7+Er2ALl1JdA3OSIDsy8FqU2A6CHGnwWgca0bcsWas7Sgg5hwD6NsI8LYBscZUuLlk08iasinBcfIxN8By0HSyzryqIHnn8PXktQPHN4evJxvudDFdUsV6OA1KF1O+l6qLVPduqrbtYf6xGepYk5oAJaa/xSBCINly3rIZZt/aWuuOE8U5EuXaioZQpHLlKDePQQAiz+loYG31wr5bFZlXk9jMptCz6WYjnLuBdZDZuO4AQbf34S5KkuuW8s2NVe7IVZ5DUJTFDl7pv92AFfixW8Okgw9X7JY5MA2kaOflPxdTeh7z7qSanSbVaYvt5GvnTDYhcx4ftBOgyYlrHJQ7z2KTfI5UzfAabMbvi7ookDlPIXkmRIezU3hx4hCSvJcrttWhZ0C3iVjm2AFfOuiB78CTsGdmGThKw6YduTJZLIfEvkgY+qluHApM7CtqnqcbhxwSO4Xdhm3dmBDI2Nc4FA8pKEy4k5GBH2pwMjSNSg0a19wsboH1a7lq0Nin/cpdmJoRIoAx03l4cJQmItOYFJgmTkBGfZnK0XXFEsU8bg6JPdszVr9vnsajiosvVtCMSIGJK1bQjEMOiZ2CfsXAXQpaHJ5DZTLs5JwwCmwQw+5Yg/NzqbQo+NhjObBWnRtB41SBxUElgfpctTMDdDIVYFxRtm5EONMhqqGsZlRq0AZF2bpRIqENiLI1I8RwCEtblK0ZkwKTuOkw1pvANxZ9dox5bow+N4lX7AIb/lklsH2LgZKBDURBLjvQYY27+q19XMNsGgXeiExDzM3SYXGZpuWLto9JMz64EfBgmEKxZe3JpUdPCBnmsnho5wFzbYXoJOTJN6AXvA0IYjeVWwPU0i7QeSSJbkQqiFiZJPmyiEZUGpDYuSynv+GwjcOy6y5D2gY8rQphWAmkievpgb9EwoB8d/eJBt5TBzNJn1m0ILi4J+4kCQuUc4AVMBxtcu61ag4faCXSQMXOSBcOPKjJ5lsLAg1I3Fx0cikKKF4+ehHhYKCbaw3zK40KgbsE0nj6pRYq8gIIV2yiBfACCW9sohp8HYyIQWsjZPGBH0RPLQPPimV8y/PgMHqZrlYKjjMrbZPBNZpomsZhtYAdPYVJwDL05p0SySQr86NMfW0DQAlpXKSbycF1y03o7iMg6ZnUoszpckOSaGr7URpIVST+1lAodryavSh+WEUqMWVybfuyPBSKVu2WEELtTvMMkwoHRKoVex0yB5mMbHccASLEv9DWTlkOhmSr9jCEgXSxApUKH8O6FTsZtgjhZQWq6Ze6Vm7kP1gRMNNwHVlO2yJCxZS1NywVyQOlRevw6x9YXRkE/bRUVR02WqMC17bGpLG978FdFVlAYRSgb5WZJWtF2iD1FnH5ajYOULVZmU6niYmBD3GltGIeDSws+IshtsoAPYdfgzKiZnnmFiRCEwhcJLG4iFa1uTC90nmpwNgmS3av2nBEvrTse3MVwW8fgmjy5HU6vV6I7ES18PQGt16n7y43d5sA2B+h3sjcWFvHU9kKtRRcC8aJ8luyCqJ6TJ3bptgMX4MkotS1YNaPkZOqbrSkTeRugjgxfTtl6rUQEibvdx+QFXAG1dYOTaREWfNQMMw/b8MmxbrWZokdMlpZLef2DE/TQilqkBY6eQh2TMrMS1AsMzua4NgqYIFLIzo1VHw8zEKwnoQIeFwLXalmjAhYTEzQqZhlU6AVmQYyxsXTaqULdKpCdHA8/pbt0dOHURPYZClgitMSSFsMTlBwrMQyk6cQqFvtpzMhgbGyyeY+NGNSgmJk4R9rxiADxIg+0M2TAh4PCu9hkLr2J9/90MOhCus5pB7RWXAmISHFqKvaWJGD595jkKTqFo/onNpBsrL0rK0miZMtDKkAedg5YOVuteth6tAGRKv6EKIg4+Sj5FgIRkY9R0PUY9VMk1ZcKpikzHC0Ba5d6z2q7JNbpAaFfbUN6osTC6pRzYACh4cFWk3G/F2FbWONSh0T9xqoFjy6Q+6WHbBofrKstnrwaGJi5+MGCeoJ7qffyUvnQuJh54Hv5bEDT/EolTwysoGJnQ+6a0izFqwBiYNNYiWpLjRKLOz4NXIqLl/CKSuK45wcfQ0Kc94G9WPKh42Pmh+QsVBRO4mAqLGxf+XWAiaGJSBqKSyt2LVNOwIOOi/Hkrunt+BmINXFFGg7jHphUAlMm/zRzoAtw4OeUaaeQycQo8/JmQJ6eulVSlxiS0BSrlb9GoChLqcGOxXHYJebmEMnELZymCIQ6TB/V9BBBTxdlN6Ouj8qp0KXHmq0I24NLWhAlUBsgmNpJOmZMFRS0/UGWXrLTm0vLe4Ah3YBVe2RLUhQQ9By8dSAUAelQE0U4xS3yNQ4VDMLOcMc9EoWH+Xp6qrxN8GwU7BBlEDXsq0EwCFPEEndDsDMhYqKgZRa8EwBJna4bP1jggTibtBtaFjcB0IwvQdX6oY0Bn+pwpATF2cmmiCyaWNbSRvlCnHQC85WNeQcAQtYN5Qf1jAgrsJgga0DZi7A0wSQDKj5wsmt3MnnfrxMozlKi6oMdBsaRhLK2zwKECboin3b5a+SZTemtkJWYYgfaWSO2DXQaI4daAfPJJsIWI4ZWysgN3rKAONwo0210Y4W2nSCCK+CkVRodBUVQyRU52I5jos24KBDdKWv0+Ssctekqu62vO3HbjxFC0wibajtQTlFG1tD2N6a1tG5AIC3B0fym1MSYUNtD8oJosYawNYAsa3+TwatxfO4m+plYEVOZ0uNF/FGzgRldw5BTTIbSKygXHQsLxLMtUoYM+7kSyx2gtXu/qZca2fIUT6ZJ2CmkfRTP9rRNjH0hUvuka3AvHXFfSjDB18NSkJxH8rYDdSgJBT3osQ3oisCWtPdh/UbUFH564r7UEbx8dvXanDWVPchDULLD9UgramWsPKCk5LxiVFoIgR8h1CK7e0jRkldYqXO1nborWyCbAc2KmIpFrBHGk728l6hg8jz6B1I5mvzUywY0PBJHFa6E6YOlNzIhAfmAZE71cwpFSfbkMOVvupORcdquymmRKnWYx2SU48jmxxtQz0L5tqZY5ODbuoX0qDj+WvYSZhgu3a3nXkKjO17TeIUzWlNZS3LrwFHTiNLdrgT+EedNeEuDTQsPl4zlWoOTTg8Lk/8Sv5Sn2zxQ8+1YftlQsjm0cHR69mb2WFZ6PWU5ZxnxSm4Z+IZ5oOTwHfF7Fok+e0eqs0Clwq7J92Wrph1QjZUuTaW2eggPhJ50AMbPprqnpq2ewU8JmZixffoMlo3TgS1GkzAe2H0zaw7wLQ9K46zPCJRE1yMRqdr77O7Ssyt6rvtDJ8G0ZT1baewzwGmrmhs1Qs9F7qiOmBmaKXKPnCRmF6VFVjUH96acRK5WzEHGbDB2insAebB1mhKXIW+PnsJW55ltRdtUbY/cO2N15u9l4hYvYdUvpROUz2i45wMeC8MpgZ9OjvvFPY3TeivBDyKOQaN0Q1qapmaqung7RT2AHuK0c4eManqjNAqKlna0QmRFfpGTVCcXizmi64x1Cl0ne4V8vnW9lLKNQ2EgbLqPEnYgCkZCLeRQzOa2juXbLLH0S3wsqPXVqwV5Z1Qk3+huV9Yr+V24RScpGYGe65tuQPtVlvmirsh4hZS0DlzPAgrejsB+mFqWpH//YepERKK+dcPG83F9c3l4khYiwIDhAkMgjHXvCrX3FloQWwmri1mFywPwope/tygRZBGlDOh68Rgz4h1yOzxqtwyWAapWfx6NvA9dzliUhH4U0wnYJR45ELo64hQ4HNLyeMpAtSyN8EVPjTB/AYBiml6Az4XWf4q3crtrghgFYXdyKYISghkrYFIsywlz7rUSrJ30iV/ylyDLYgkT/I3sFW1jltB7N/ZDAcDvuVuh+SxEo9ESVBPhm0YFSmCA/HEitaCdqq2mbTY6ZGzy7JeIUKjAaHRBbecrlMbsGE57tadnkZdeV/+GH74HkRb4CnDulPfu3up+rzMSkeH29DPZF1UFPniv1J3qGBgs3P1JWXGroGQs4d5V2Wm5JnPDhPKeeqrKqwj/F+leXm8iGFu3gMgxEfljj/uYydrogaiULeb8KsC6G0ddo+jGy4mKtQaZhoKOY1DxTgTMy2XtaoAOEpHDd46gtED6fqvZBGizMX2TJ5k40aOGVpR8tQV564iACgxau2prOHri3XdlimmWlHJyw9CFjEqxI2CnZERMHKERlvGUAOrHQVQqKCEsqFoqyB68DogjAA6HcfJzpzHu2OlzFAwo2+H1MMlywNcQ/KhWgZ1ID24P0ExaHpNKeYqiB68snIVmLHSkxcaOH0Qx9YamMt0tZLTxDMjbkLpwx6m2XHO4vYIDMbegMKAPV+yNbepvwSRegIUPAwsHiIrDHWAXwXSgzsMosRaCtprMBRzFUQf3ij4J2zn1dq4CqIH77cUpGqNWyLoQRoDP9yobfd2EPqwJuikWN+CoYtaT6gD6cG9QI9fqIddw9Fr7QhYvg4dYwNJD3KUg6YUcAGgDyca06l1iR0E5rl5cvNH3oZTh2fEkxfAv7C26/6bfjbACs1jGVM3vVYp2Bg5WGOHhflqgAbxz6enLNc2n1xfmKcXx59Y7vBEONUaCJIyCsRGAYd2+QMFOW43lXh9O/wSE40D7w1XLMta5fBbRTFWlXdOgBGDVBVI6wA60crK6+xFSUvwbKDLIjIV8ErN3ZOdRC+rAmcDQXdCJexk1ThlqbkbX9a1KgFYquafw8c5c32Tsi2ZZ62Jf5MaAaststAIDMNinLYkxxrbQr+sTMc+wkVKYR1HTxBaPu6HQSBl9YkbeImEqbzGLoHUtkLXUmg4XdcKw9hI4G+m7QWpYzwAK9mAyFyjs6mBHxizZep6jhF7tlGIz1h+II4mKyCcgZWVegnE4FlL4BGf4LOCTgM/hG8s8XkTqBXPrx218L1W5r2bWO8PZuh/JwcHL5aRc3xwcLT76AcoBxUKRcwaivEPDw/9dbK04GMJLBR7AzHXn4XfwWKuf2oH/iw74WgGv53hITP8AP78vthRPjP3D18f/PDm3eHR68r2cj9wgPfeAbEduSEyxh8/GM3PsqIjjAY/+4BnaYCdwJ/3Xu4t5hdXX+an85u/m4ub27P5pXlxeXb75Xyx937vH/++20OFAQOh80fsgbDZe/+P/315txfBkvoOHPjryvJi8LJ8MGtU8HOIIdJdToqflvcLvyy/u745N8/w9WImtCb5XehW7yTefY52edPPqqM/k0RZZSG+zfcRUaWvw+pxaMRXeHUfFlWUb+RqkYBPWs/80PxueWk240s8kl9m6VttMrIH1tn9fbULmtsf7HjCPYr7H8CZC/CHg+5HwziCgYgVxm+OD47hh982LM93lGh+yx+6Dj1yfSt6YiJNPt/zID5XwuERXX2j59HUC7mRk+90PYyn02L3X60umz2HBKbIN1kQVB7ueArNmbc+scuIaHkCn8qBNjtCMM6y8hRqRGCTlaKJkfd3ex/yRun9xQX+8MWj723j9/mnH+/u7vY2SRK+N4yHh4ei1YQkjTg2rrKHZgBVafTki7wtwq8lUZp96Dr499SeZXpn2V3uqZ03S6hPCmAPZdZ7pNnatrGE0PEJkX+8w00snilCicUx7CiSBAaY+KnZf6O/DfRQ2eYW9P6IzZTDhAZAEn95Oba5tdIkWMMuFrWpp+XJKXmZFF96qFOOUE+d18lFcDrzHOKZfIs6ft+0rcTygnVNDHykcV5c19eNt7O2Bp30ZYM6RuRaMb3Vqz1CSNDIp26AjyI/8CvyKvhnBhWG6Cog9J021s5VXIDEcqCv/gpMXsS9L1uPGuLcIjpKUL7ncJSMytaLoXIquwsHiiC2/w2UQW4VZRfSse1uqJDKzjheEdQNaCxC2s5+GfBumQvG/25+xhP/i7TDlwZIoR/MM0TQGBB81Zt+0Av/m+WZJwNeLY8lGfJucQQM97u9J1cNkTjaBRqnbfC/SzsRZYCU2oEa/BLK4xsGvFoelzHg3cp5Ftxv957KwiKxZesq96tL9lrRsgd0wKvsDUDnjkBuAZX9odzvcoYRLBtgRMip7PQYK26312WIpPaNhUOl1ff3iZBT2Rg2VtxuK99wSfSNX6PlDS3J7t0Yo2TVd0oMFEbdxDNKFm1zTYfA4eslIoX2h+9DVuAGiaNkLYyRU88pGCOLlhkvQl4tVU+ESKYhyaDtIyLktW/oECG9vtlChEyGkcKI1H8hUhtJ+aKkUjLlRYmuZrGLkFnNMhcir5IFLkJemagtQtgulVqItFqasxiZtVxeEUKLfFshssqM2DHSGMaMI5Mt5Ugu8yCFiG+m0Y4RW6axjRHSyDEbI6xMBBslpEzWglIq1wO8wnKOUaIG+1V8I0VQcw4GCIxr99cNllK7FWuwHOKeusFSiFvPBkup3Uk2WE5cS+MYKKV25Ry/oMYtl0wiGO7cHSCncSPuEBnVK5oGvN+4UXaIjHDU6wMN0HX1NK+cmLgemultB2Tj59ytUIKG4dspXhwz7I0bYnpLKwacxmETjJZXpQiuT58KlEvMkQqUmz0oWC5qJGw7lAMaCQdRFEQS5Ia1zDLBslGeSmXSWKR0tACK3UQC+jzFT4anZKL976FouZk58NcCRaP2zr26uEWj7XX2kxMk8LPQT00rdNmju+G6GqWNM07F6kU6HABCPJ1pxoEtQX61PoiVjvNa0zAvfcGyq44lRjS5QIwrRCCqZyJXGitJmMES5f/AQrY9KwKimOB8yaL1T+N6QqU4+Vv4GMo5DSIXpXHJUFP4aYuqsRZzIhctA+az5tlveXLLWfZLMVOf/YpSIUV0ptx6P3lWvJle7fzodHqli5O5AqVXCpTeLk6ub+SoncBfPyObSamBn6WVhjSHRk4rxRbSaoO00pNWeLdnFydyIGPJcjDjKi4HtNDWIwSRG25AZHlm8RGKhqz00YzACkRgawPze+Alorr5HsW2F8AIKQ0dlPkuWReKMCxn/IiQQQ2SYkVWImDkzKItmobU+LkWBi2ONQkZsIIx8ySK0NbAKRStQ8e3JlEUh+4UetyjSTzBPRo/AmRQg1ddplAUPvhTqPkGJnGCbxM5G9KTJXZMoS3aSu9ZsZqpmoR4miZuIl+Ip9KDlwmn02RugOXsEjGkaiRSPqRqSifycaSnyKSaRF9sCVjd6lFUTlX6x2YotbjQHF/7MEPU0KlFMTHMkKyrGGZMoAYF/hOoQSH5BGqySHkCRVmkPIUi1JFMoAeFsBOoyULYCRR9m8huU6nJ+vkJNHHmvY3QlE5UhYhedwp9uNcVpSgK/GIerxyeWfa9KzD8p6hAH9nevbjuvE2HwHmnNhXiIqAWDWIngtqUCJ0EalGycsUN/FtUiJ1jalESBg8gMmPru/RiETlV0qJC6PxFiw6RswktKnDuuXm9OHyE/02jTExCUZ+qysZGaUqEjlA7dAgfnbbp8sI4Rj2MMEXFNs9snOZbW2td2c6KB6jEV5IVE0k8pGJRkQHTjtvKxlYpGhvbcpHCIndJbNCaJXN54Hu2LShPbmfPjh8i34kF12+aEpSPKFVB6An0AZp82fjFd+dUNVFggzgOoCqwjQUuvNKURWAtdDKariOB7/JsGRqkReAENE0+/CCcokRQRTfRuE5ymyKh76NoeXhwxA18qgp2+4rYdxUNkY9bRZkKUKsoVf6u1ZKpRlYXW04IVaqfVD2V6idTz676ydSCq58oBenWXbnAQXsWdpGJaVv2RlyHWNcRFxNbptCJB4qaLFgUmVbVqmT5zwT7M4isJI2A6F6lVa/I0Vu7kimLS2gGT6sWkfk7HUrETXO2KsHHHk+kJj//WL62OJ7AB9CJ4WLHYO2qhK6XV9WU66B5qy2jZyCmHEQuH7cqaWlOpesVuXDUrqTSnEpXJnSZt1ULak4nUCJu9bBVSdacTqOmaE6la0PNqXQlu+ZUviqhC6GFmr40JCnxD4tSURvoeXVXvlfCvfK9jHitZaW9lf4E/tamX0T7urE80rx4Pj2w4Z9VYkYgBuMjFKSD4EDRMYbHgxsBD8SxYW2WprtNQLSy4DOVrS1j60mPBkFnhvRpwe4gU0N584AU6SP3rfdID+8T01/747y1RwfatC5TPhIKKwysH5HzYOEIF13+IVOjZ22pd9DI04YP9pRXU9BEEn5DngK0eyC7Xw8dfjGBmvHj0RZFxTgRNcjI8fxjc2ygy6EpkKYJnfWWH8g8gQqzeEyirnwEnMrXMT5a79RCVh4hatAhk+UK/ciJqDah2QE+UiRLaH4JFYnQCIgqWpZ16Jf8CdQgyzJSzSIuDCGkJq4nGOyu3RJZK8sVYVh31lY4/mitDulJIkt8go0iQ27V94TLlyo8c0GhYgkXFCLZjp7CJMj/KU63rGX+Ed+J8Xy6WjLvj1Qrku3a9mszUPa45SWaAnKK2hYUuuUKKAUklADKZCWVoE/EqyCMhFUIsdLKjXw85EzDdWShK0DID7KjoCdUJcRwmyBO0HAj/7wSeZpbOzTR12I45QVfNGLCaj3ptdxHEvPIRvbH0F1Rg3NKuoAEwbiMy1GGBAVukCCPuR85E0oXjg9wsANP5PQhuWie3ZguzXE4D+pmFyzeIPiibpGTQ9lNWsVh2dltAoLiFwh3C5ICOfxRwO6SPuG4Fq2zU/9rl1qLVOhijUKbyVx+3jci8dWWWGSBVFTkDScs/CU6NHUVWT54CKJxiX69+mhlJF6hW9Eo1oxRo6MUKZfoawQKdrPGI6vwQrbW0BVkSbywU0CX1zPLLzoRA8motnbMtatVAs2/BQjl7pA6ZEXAQdsOLI7Zi3ZpA6OJdoF83RhNjiu4IPJYOPeQYT6WVzcMbGnFrk0Uw3iZI1pVmtB2E7JKLfaiwWYRvVff8bflCA77RQ2oHwxCna1QcasgMr0Hl32IyyCT+8ITBpnCBQ6o1t1S3bzM8cwab1zEJlqsO7kCDbsLcEbXxUqslLdJIEqyu8sBHKcEHEfZM6vIu2r2No9B8pCmlEFsWWHFyKR6LbNovA6Ip7BQbcpu5szD2cpCIf0BLi2NjpTdY2lvD6lLVDm1UHKcMDJsHCeLs1pTZXA3YoWUanfNX8xEZz/EJfMS9mGpOCbYrt0tqJd+9Ttufp2ySR8fK5oMfEjY0CT/C4X7gZN64G7v/d3eB3ShKVTy/uICf/ji0fe28fv80493d3d7myQJ3xvGw8PDLBvIzKBUAw5grrKHZgDNIaInXyxT10vcLX4tidLsQ9fBv6f2LNM7y5KbSioL/GuSPllBCLbmA7CSDUqIR5ELrCuztW1jOaHjE4L/eHe3ffHig4uuMIjRdcEvQiuB8Xumfvbf6G8DPfTBqJH8IzZxDhaaAUn85eW/y4/OH/GtCDH86h/IXhGE8R048NcVbJrB7t3sjuvyOS3s6oCVlXrIqvCNdfybYUUZ9hT3eLmMKzhc/BG+7PxmX1H2/dVZ9m7PSpNgDbbGLPZsPGEOjJkd2eVRopFODXJqF+8rN/z/7r3cW8wvrr7MT+c3fzcXN7dn80vz6uxisfd+78OfoEnu7l6gFHmo6uPd3uHs4G4PfgK2duDARg9+dHvzaf/t3d6foE6oNNcJH9nC8f9HGvfTrEi6qSMlUFYIhxdPCxv+C0UVsvewKvgA/P+HVeA5INrpywqceKZ4EgZuu+eI7TOpFVUvt4BPQV9Ce+AALMDM9OhDz93e40+wJ2Z25lZSS7YSqQsHIhFYo4lrZylJCZ7nyHo+87vlpVkkK1KDb7lbE18iZ6KLn2Xw+BQBcH1zuTiVWOYoc0CqU63zhUfZCiR6bL7gchSb7tZN0A8HUjXF+FAg17fguHA6PdINiNThUYwzBbGqpkmoodZzqlIjdU3i+jLloxMA5cjH6SySoO/OnpNa3Pgmztj9lzQeWf4J3nJshfGb44Nj+OG3jQx11zfn5hleBMX30Qpmgq+cz2GnUZk+JkVFEgWeUOGhK6sO403CGLhM1xmP/4ORhcnVj9zsQsorGHzDX9PIRYqT1HGD98XIwSiC6UxWOaLAv72QMzq4AT7a9ANkjQ/ygSLTACGLS9BctF1GueU4b2f5ZnEwlTA6EU2mcFrvJUYBdrUIfZZ76CI4nXmOQA2oNTstZ2BFW6ecEDVtK7G8QKx1oILGPLM84fYw4UNbhLL6TNYk5A9cgATlLVvK2wX40CzX4KLZp1+39bnWDgYbn74GQy2LxnRP0UhQnm55J8sVa32+5a1sArDnrdZ3YW/O9GqLAN9OOV5vtVXUx5pd1sYNB8pqsxGaoh0hsEWse3Vxi5ZtaVOCIlU4QSICP6mIaHjyW2MS4Od9Og70s1qXNRfo+ffGJvCB8fjwaDyibjqGBQVc4wZW3EtYcY1iR7WxcH9GOzUMWN1io1IBWY4bQZ5kIBfAa6CliY3SEkYr2GYPJ9BE6ITZcuOcjmYhAIoyBaU3US2oFrRkjpCl12tQMnU84wuiThhNXqehRozrgIRTxgfExOhsC3OVbm0dSFMgSaHtABDiKavivAUdiDdAjaEuoGFo9ppbMf19ozhAFAXFoEtZMRRb/kswwj1vacVgl0mmmiuJRjhZ8vgv1WRJNFLaFNsOKydnqCbcRCS9/9CEdQ2SFNpEnKwL8QYo4dSh9N1OUdWUCTAyqOpTmQkwMqhacQyyU7c1oLoDI6vJ0qveEoDED2yqIycNGNfxiCecraJr007V8Ugi7H8P9WGbg1E2gBn3MmXGGra9YudOpYylylXoQGnQjc1FnlsRjI67ZQxoRU1gdyWrBEu0mALrv+1Z2V47tcVCnnbfAvFXU3FbMot18xkUBmy/452TbhDh04bKPHiFDoMAlNNT7fiUV2vqWBwdCKlBpJcZsQXUKMsxu5AW7NuxDTPCQMcZ+lpjRTq7hkDY4qwfu3F+RIvY9ur0YjFfyFimPRsPtlP+PMuukLtCm5EwTxUO9YsLLaouYOBSMzJ0Rm4JowFW6spsru2TZ8WbZ2KZEusUhpkfnT4Ts+RIpzDK4mT+TIySI53EKFfPxihXkxnldnFyffNMzFJi/TXmf4iPwD8jN1IybqGWbAFHYLD9Wa8q/VlAvX0mgZHQGKjGWa8eXUCvXeOnV+csoAOu89OqUoqvk7dnFycaESzgiGSoWVAgpOOn1EJ9OsccjeBaqBE/4X0/dnt9CBZwhNdCjSgWeCadKSxMU5uWqty0+wwWFpqXNasr0/6LpMUvjbddIq2rFSoQ5SQ+m7ZlbzQzQQ2YPC+wHEXJ3r2FnyOTR335z8RMgB+iLY4pvkR1GweRptZoByvPQI5vaWqNHJlE6tmYuri5W0cTkAjlmQKdn6SpDQpo8sjnV6dryD1HJpO6og2IDNQF7TzsOEJJU+o5MnnU0clR5c2+GhqAwCfRDLEVJbqaoMCmPMlo0gTObEikdCKsWiTk7WwFtomGaxpboQJR6nBNKxPUgMkdrmnFvI5s8uGantZoByt3uKanNXJk0wzXNDUBiVCGKXQ2wgT0K0NC3diT0OSOVvXkniOTO1rVlbqcDfbEmFBP6jmyKUarehqAwCd7tKqpCQpsv5INVFHgS9mUIO0kGQTY9u4VN487s5UDpiowKUNFrCBS3CW2EY/kHcWB5AP1YWALcyAtCCw0rEPlQ6EW7iUyOcc4WPa9u1W0ua2DeQWXvHquuP9rq+byDu3AdWmVxoqnwtpqeYFMGveVq3g2uIV5jksa7+wOz9j6rmfBk/DkWeFBz9LPcUnj/U35/EYL8W+yZjcKBZGGPVsFlzTeibX0gHm9OHyE/2lpgQZCybZQeHATkyXkHeRU6lE/59FmAWmzHYWGVNfgPpUZ2xcK8IV8oaaFXwcozxJeGMdo8kBPM1TR/UqmvWCJuuEGRFaxljP0nI8W+dLOEFKe4Ny0XJnhLSvF2UofzQisQAS2NjC/B16i9OikHkt0ohVuG9sL7HszDR10PZeO5qgDlHMyc6RvrcixyckesvTlnWOTwhuoz2TvYA6kZbEj6dmkq67cS3RyuCtP3u+iLit9HwlXnr7eQVxWAjuSHYSWH2rLvEQnhfs3nb39m0xv15m4VN5PcZTo26Xv4Elhjydb9G3mdvCksE917tZTmb06Mc+iswWqIOVYQv0+nS4T/Eft1ClmNJROyVFKo5iak7VDoX3+QkdLdKKVO9uioznqAKXNtuhIvoJN2myLrrxzbBJnW3RlLjcBT4Pkuw7uchPw1G8+6aIuM0EDQbQiK1G9Ia+roSMgyrGC4iTELvbyEhE1SELsau2kJiIq33HVwVzWnqtiBlNf3vK2FGTzl7oyL9HJSS9XnXLZwVxm2uU3oG+nnmOTN5uuLXGZ0QwSboZRkOgbxJMQ5SRaqU647aAvNelW6xFMJHUEE2s8bo0ljlp1bupktnSx1sSlMs+W5rTlXsKTyN7cAMtBS3R6W6EKU+Y6qq5W2MGTt46qK3epSfX6JNT3WEB6Ur0GJ0h0mUDEGRJU7uUxFf6xGerZAjQh/kq2FMQgQgYRu48gW8/zra21FnITp6SNCt3OSJBQm92QF5JBQCLPI22gFVBLhV0GJyfzgaf4lLYp9OIjmpUGWi2KT8rd9h4AIQ6mnmHDUGI3N1Z5vpYG2Y+Fh+0Alq1DN2Qt3KylLKW2Em7NMnq0EJXyy5oHGkwtykyjEKY49exZ7o7cndu8Q69+m1C7SWt3AzVBSzx8e6dMmxshOAwk4K6IZ5OF2uogWhyP2DfGo4CWeFbuszHLNLZAKULKr/blMUkF8GRt37MwThPzr2XO5ClOgO+B78B7BhEGmrtbBo7iAcrOZOXGjByUnNSo0E/1Y1ygkpMZ5Hn6Mc5BySG8O+ROP94ENjkZEsonHSi8pW60BH6oxf2QNOI1cNJWSHGvqmNrXgMnZ4GsPNNJO/oENCnkHx4cxZssabwLVP8Rw9oialE7V1gphWJtNgclZ/9YrMNJhzTWVWTyokjtaBeopEWR2jHOQckhrGMRSy1hTY6upvKWf251GAU2iGGYpsXddVQjUBDKGUGAtfqcW5oFKsAkEU8gNlf1LCOdegWatHGjfrQlptlWh2baEa+Bkz5u1M8AJDjJ40bt6As7priVPB6hace7QPXclgSGvlYfn26soWsHwlcN2taccL5QYMM/qwT2SzFQNP0AcZCL6nRgwzxJ7MrQ2FkHjqJQUqNRURBrfHRgkxYF92v8L9SL+cGNgAdDdO6ybkhaekNTr2U3A3hayQPm2grRfZIKDjgsrGxAGLtFwxqkUf1HG+Mk0Y9yBZNozkmewqAV6QYo8ayhPn3Y5mAEs9SvYOWWapq4ni5MSywCOZYdrx6+W4fzK4zBihYYO+zkQRdh8XK1pwJHQv+X11BVx2e2Um7gEs9dH7Yy+JFdqiZUG6CksdbLoSmwZDHXjbIErvo5tlyv1qpgpZVqGqtIO6ByLKBIiVc1oVhgkRWvqqdZh6P3RFVh0VqA6wM/iJ4GTxsR5eNbnhfY5jJdrZRcYlGWUEbKaOLhLSJRVrajpzAJRE3OyZoYzlAqrFkZgNpm9hKUDuPBDA1u3dxkaLVpkS13SyiJXGHlzAuZxFM7f6KB9T8iI7SNv/IKWSsrSv2sYn1uq7AtRby2/edUvyFc9ZUagiBrco7qP6v6ItLK6ywqCnJ7qT36QGWNaic6Pu05VU+EV339RCjIClrg+s+qoZi18iqKS4OoowWu51ZJRY2TVm7kP1gRMNNwHVnO8HQGothrUi01ybpl6ddJ1j+wxmXsspBX1xCxkVc4VB/eDVCOhXpwV8U+hDAK0PcKTZ+1+22ghDhbKT6bgVF34CGddBOVINZ5853lqCpn20AjimUxsat2AiEnWQOjrL3wzC1INM27Q54P0eUOoUHRYWOVlZIKTeyCwU6FbXne0rLvzVUEv30IIgUbv+mG6AUp3iSa1OSGFUZWalZfcLcJgNEGijXMjbV1PLWtdosztKDUYR5c+BJE1hion/HMy6I4MLMGakp/1MQG/SglGUU/AzzbRd5NECemb6fCohRkDaH1331AJYZ3f2zt0ESAFTbIhb3yz9vQPUtfsDZLXJGjlTX4pP4ptougzUCwCNAdCTAUUugMhMHKfOwmPLHNYIFfK+I1XHIYmwUAXakTAKWkN6XacSeACeWMboErm1fNaDewCU7YqzYigV5VnQ5Phrdnpy7pxL0J7Vc45NIi8Ze0vfQUYMdKLDN5CoHKLFk6ZxKaaN7ZTLB2nEtYgvn6x9pxzSAJ5hno58eBDP8N7+FwbO0rOKegh20V2K9ruwKdr6SNCwggCjQ2VuTgteAYJKnKBA06+3aYou3hWVttNpq12IIKUYYdHLBytxr22HVwEkdFOlGnYJPEXNFBsYzchRwW2xwTZYg0Y11B9SznPIcPnbpzINSVUl4uNTBis1kgpjixIBT1PCmARHNFGWjYkq7SvqZGuI5KSr6SJmzHDgdbzztDqzllk6YL2yYqsazdIEH9872K093ojElEYtmGUZAEduApn90hL61qoBLLOg5d/VrpBijBnBMrSfUhW6IRy1IrNxbuvTgZV3mkm3OsgZGeR8rxAtOjPQ/1fV2PlYs2qydgphxjuXKZguyRyQMt3rS0Ytc27Qg46MRzS/a5bYWVDKS8WDRqB8LuVC30pk5ebec3NkO1bceADgw7obBQ5Knb4wapbX5S8TupLStpvmpTWoMgw/VVMaMikeL6kzPshDK+DKcJUjuKblhA2kJnyhFlO6cxI8gWYhOEne18BoSZdBqKCLBCH9NJ8Gbethhoyp41S6HdKRZmIsGBbwwiNAbgjXu3IEHNZLGpUE0IjFLUJ4t9c0MZNebV/SsCw18kLoup882q6tk14YghaIMogZXEthJgxkkQSd4szMyUimskZdXURg9asJtn69+TbKTrptSGZ6xjQnim9+BKPrqEwROrQHQfiWVFMUnE22a5ytYlYaEvEuZs1RPKMYyl4oZThLsMfKpAxpLSg5EwOlMNShg4iRuibGUvyfWzGT1vQeltFFJqwyOAogatOAXKaGLK65QrtqEowwPVzUQViK4j3ayi8A50Wceo9EOhk00ELMeMrRWQHSln9HDw2KacqWQajjZJnF9BT6rsxszmR0Mj3aYtLMdx0UEA6Mq+CVbkc6vkFY2qfFiZ2n7sxtP0YSSHhuKB+KfpoWrYefuiJm4XAPD24GiKjojE3lA8EP8ko4cadM6BQnsLNiFoZg8X3MktAytyuPs4nCiiYA4XX2mDEMvtXLCKMh2muC+w0Kv1vMoOqVTnJSxUXjZU6B0cppZS8s0yaTTBKaTtXJooxgTg7pGtpGjqqsdwCB98VRwI1WM4xG6gigOhehSHpzhKlLlTXfsYJt+AmgarrnoMhyg+fvtaFYua8jE8gtDyQ1U8asp1nRXINrfhU8jRVCf4DgkVx7xNNFfQBUHyClSH5sphMO3QJo1ti3StCYtFftpIoYXIxRw8WZPns02zNEtDru3UjTtpSl5pGzLNcPQEgjvd2hCVwbiBuDtBnhoV91h7T7PYQ7X42Kky6sH3Cng0AIxhUzvRXgGdJgIlXSFe/YPdsQm2a3fLncU3smesaZ+mu6kpre1haADSsRMiw6hJvLduNcKZG3jG1M1aEahn1wQkp6pSvqB91Jx89UPPtWEbb0Kq5tHB0evZm9khxcGam9ZyW7U6o6A10BHrZUngu+RJLnGSOm7wHpXrrrBrC13lW8Pm+5duwqsyf2XMaloQH9GOFmRQTnt/YBXciQKPiZlY8b0ZgbUbJ7WGph9Vr6yhK3cOMG3PiuMst7Y+HcxiLrqIoRYbDahVxjALQSkg4nbg3VtDy2WQ547zV/R+6NY7QTa95XtDNUeAX2s0PHQ14yRyt2tenbu3Bmr1YIXlVlq8NJRpIzWCiSlbTsOwmG1wqNtsnW1GXnkyC+19Ca07H6peWaPaLk4L7d4aXpfRXwl49LlLp/buqLrNqXv31kCtTzHauRpz6628N6ZV4VVbvDTpUPn0YjFf8Ea8p9ArhuVDzLe2l3Jd4VmzblYv2TtGzM9AgI1ct9EUMXgVKRP1HUQxU1zUCqYiYTCW5F9oBhVWVIb+jAKEfH2kRdY2w6im1Rr528Mx4Eardt4zM4TKy4MR+GFqWpH//YdBEIi3p1oZbKmw1zeXiyOldR32waxWxGBrzpS/Prgog9hMXPt+GITKy7LzqBZBGnHd3dPkCTs+jLa346pSzfQa5Ou6LmcD33OXE83vAJ95rIph4UCfeGlA8AHfX7KMLQiNy8G50vBl1pExoXHUwBi+H1n+Kt0y9DGE1spbw9Qyd/SEWs7OnWZilsF4zcCDx+L52+YabEHEMjvZUFx9ddp1n2GnNcDg27fcvnnftpc5M3xrr0dJwJZa3FFiCDwcnSZWtAYMw45iw1JOO0v5hTCMhhyOTpP7wLvGoAlrd7fuQAZ1CWMyw7CgexBtgTcOzE7GqM15VVm91ZGOpyFktH2QofOF3vElVhE03lJVgePMVZOkdS48UQG4aeezjIQEUVVoFBhJHjvaQDLcYuDcrQdAiG8eUHPO0E4/TztQvLOb/qpKGdUI7ESh2+p4iroGiiZK9zagYschxMsljqoUQaUxAlBdjPIBZvsX9QJFKWrsKQjJxo0cM7Si5Ik3jF1FADCHk423s3Z2TCjrcs/3UH2mJykCmdOoWMkoaBsZAyOHYfClSXQAsqMAKt22D8GYIVUljQTlgDAC6PAtJ7tuCG99bh/4M0NslzsScJZFtYYWCAXArEsbCe4TVIOms8YDq0oaCapzaZoZEM9adQcYH8SxtQbmMl2tOlpyZlhNeWMBhml2tUIz+3sYwIY8AQDzpUVzm/pLEAlCSREqAOpDZIWhMIxVaSPBhUGUWEtPQHNclTQWVBT8E7aXAqxVlTQS1LcUpALMVIoZCScGfrgR0HTs5IwFlKBDrX0LdssCCq4ubSS4BRJ3IQhbTdhou0XA8oV1BQ1xI+GhZJ3xqAopY8GgEYuAEtzJkTopW0+hzlvIATF9TdIF8C+s7VrMjXsbYIXmcetsQ69RC1pGjsrYCZR+00uLfT6fng62TU3UyfWFeXpx/EnkxfDIYgLsDVkaBTyjkDnsAqFWmLgFHl7h2rGWgocBnuq6y7FLMeUgdXBxVyUMnjoiRniDodSlDIbTmdHXC4Mtta9DfRaDDdZfvj58Jo/opAcDaYgZnu4G++cRjlG+PhxA1iMPR1C+L3tKGSdCjZnZ484tohpsl4/FbzP8bpFrRAiaMhziz2ijGqJg1Zna1meLIsWsLmxkvFqK88MgaF874UZXipNSXlNP9VN3LjZyMnI/x9kwaEYVNRpRCvCHHtrdiT5ZWV4MSLN8yIP+KyvZlNYXvju0cWWNChCddzGiKEwjXL6dGtl1xLmX55cT5+mQZ9kvZRuhN2id8KGcscpuJxXQOg5x1slSRUmmW1hngWNaoVY1twoxCvyifmiGMHM3KFk3YIXpQhC54Qb2GZ5ZfKQIaf3kMp2slbca6MhKnWAVJVa0KLYX2M+mPdHH8zoDAzt6CpNAZ2jZP8XxRFoiXbmR/2BFwEzDdWTpE7HUTbm2fZ3sh6rNxvJ0glS9vFxHTIb/LUm0BJfdz6ElNGuz3N3jqiXCvH6ipX2d8NE6YTKfUMkAo3JOmkr9lLOgtCy4pzgBvge+A2UtLdeAtOcAj6ESmpuDx0kidqcOFVXu9+IUwLrWLUwsMRUpGix1nXCoSSmbDUSJwtn9Y0V1tJ54VfSsTBXdzYAuvszNxfzd4d/M868nP345N+dXP73Bc5/fLS9FTxzyi7o4vTUvLn8yry8vzJOruXlzaX76crL480C5t1dXl9c35unVl9sF+iMC3unlxcXl1wwWxHp2Lkbo10/zz+b1ydn80vzx8uT6zPzxZHFu/nR+LUk8lHwkQvT5327Or7+efDG/nMGyurw2rxbXJxdDJefgvp5ckGb9P9/SIPm/i/nPf4PNunkyN8/OfzL/Mr/JPueWf33+E0X8ycEhn7wvnxbmzZ+vz0/OFiefzvnt9+Xn+ZX558vFzTmkfH7z8+X1X8zFzcnpXzgI3dz+/eTy6vyr+eNiYS7OP1+cf70x519HFcP858/QzBeHh4cXn29+POEl9sM4v/rhxwMhjpm1Slk9RZXpDPrq+entzfzy61j5uWz4h6OkiFe/zG9u4D/nX8/mJ19ZhdCLeIRx4PtN07DJM81P1+fnKOAw4f9/ni/OYSPz9fz0Zpht50cLSAk6/9fT87y5GtyGwKqEWumry6+ZoU6/3J6dn7ETgyhu5qfwxS/zr2QzhA5pc234gbv18IHDQ2yPiw32bos3xwfH0C3++ucxcq6uzxeQJrcfXp//9XYO34U0bz6ZV1++sEo4/XJ5+hfUQZ9dz2Enwgvg9ssV9OKRQkoWWXM+/zpnf7XweaJgDx4P7FtmE2AZi/n/q8s4XtkHBxxiYHGewgACWuNksZh/mp+eoBpons0XJ1xNC6Vmz68ublEEteA26eLyNA9rGP3h+lRAQZ6Zpyenfz7P4bO+/vnq7OJkuPa/LmCIORw7fPni9ssNtP6Xk5+YMd/ML6Cu8RbDXSVuwS/OL2hN5ivmKjnKiJ+RHQr1HK8MMF3JHQuAqLlfnB+dDnyPvSJlEdDAkOKSo8JWqz1sxc+vP52csrvhCYyhz69gAaC/q4OaAeEer+su+EpvwetgWMEtHJT89fbkbBcL8LwuKhiB/Z2Jqzx/kzjAT5G225Nr/tbkdgHf4lFZaEJ9xS1HZ4W1XX05uYFjxcHjE+xEf19c35zuWquB5ZP5P1cJmebP5yd/ITSappUkkbtME2Cav/vdA7Duf/97Vnkw+Bre/N7AAfiIQQGM3D/NR0TLfUP2H6/Pjg8Ojk4ED9R/4JOXpRF8vYVR29lf8iG7CUNQ2EIsbi6vTz6fm1eXuAklp4iOOADvbAjDuJMvl58H9OxZNFgKKkdYfzm//nr+hYBWZl4WG/uHKjm9vCYLzsanvw4Vh+tTXp0qQquHmBCiPXcZWdHTJyK7cm3XpyGpj22D+ClmeZBJms/yUJw49h/+UHsyCQLvMswtg36Z41zQ8tNZas+K82ixVQL8ccdTM/SE7/4LH6ZPGNIBy7SeEMOiH/1mb/AxaF0AysdmdpjW3SIBj/v+8RTKVzXlq/D78X4cTqLaC6zEtJYu6b/BKlkN0Y8TgXtKPXsm/2dhR26YEMr/C20aRstXVpoEa7A1sifRkpgZxpHlm4vgdOY58t0Sna+IPjRjgP+NCZxZ9rNsDI6VWEL1cxTR1toGpm3CpkEF88B3E3MFyxsWe4CTBxSAgAYAjzYIVRU/1B8liTtxwRdJ/hdWiDuE6Xnb6IqIrYMvuK82y4dvJ9D9+Nii/Q9/aIz/JOh/sKKtu13HM8vzFJi+VA8ek8hSCSAEjrVFU9BE50jZYiK1ECJggigKolgFDBwAmTh1pBYYrazUS5gA+NY9wDcxWpE/Q8fRZ2ei1hG0PNYIjfZ9+MlHvgBpJIRkk/rLGoj8M/nK69HZvg8/+ZjHaPvO4ZtJQFDjNAgFfb4PP//IEbM1lOyavl48u0fb2uh9OGr4yNpQd8gPQw4wYdjebGeAmNtuwZBoPfj+ahvsZ58qAdQS0mBY1e+m86WiuTXrfd7+z/iTac0kF80guzQ74/2f888U2UYaIh77tM4c7F+yzRsItIxMLDw2aR8y7q/Qd/u776Y10GTAeKzVPcjfXxXfK7Pa5AC56l/3IH1/hR7Yxw/slw9MXC2nh8hVW1si/P3J2y/RSOgTDi2Ptc8HipgGHIkNT4Q1psH2YfwP7Pgj+naGf5wCSzE3Y2a/m74Vkqj+lsu7e7F/YYUf/+t3l7c3V7c35tn8+vfGf/3u6vryf85Pb9AK1u9n+OUxXtZA7ca0E7+x2C9unJSiyYgKYv0ZD7JJNP0vw4A13aYxcPZDC9XgRuXtFQFHc4dv9lGKuJV8dAEAAyBA1jGMifZXLvCcfbxuZHnuv0AUDxCG7fBxd3TxvgNsD5KjtO28xkU/CdbQNRnQ+zIab3hJwPlWX7Uzdj7M4dmbIE5+c+3fXFuQawt1UuiSs2x32cx1APzx1VHmqk4yyzbjO8vU9Ry8sDdbb9NZpWtfWjGo+3JFYO3p7KEZcvZZkGxAhE57+83tf3N7hS167/vUk9O6UOYHtu97YLtONh8PJq6caCaOp3pWn/+tgv5WQX+roINCvJ4BF3d8l8JfzDByt8nKxAsxvK7ivdzfRycOfMxubJygILHKtd02VzQydH4OhpUfeeUDdaa4Cz1bNOmes/KsNe1s01+hD8I30UrCfvTwCJ1x7aNTCqbvhTmKKn+6KKzfimpwUWXb83Ex5al+ddtnB2qYQUiuo8Tuw/rd4Q/+4eGhv06WAxea0JXU/lLIAP8R/lKK239wk80+nnXVsb3hFWe7kZ3CEAXGLGDrgK39NCwVSB9GW9hNOY1ZXPZEnjFNjAAau+aKo2g+GHkVw7+9+PCnRx9Fp/kt3vDhw1m2/xxKCRwYUMOPbm8+7b+92/tTJqCoorsrAO2ZHzgprFExSFK0bIBTkRYgSXDCVJI+WQEEZj4AC41PzDVITAf4wQwnukNBUGQIouRpYcN/P2b3DeFWwJCH8hQfX3OVPXYFPeHHzLzDwVYdJoQCcXktEhD+ERqd+H2ighBJTmJJpHYOVJTx6web5wtGtKa8/ugs9nAWU9J+DHrtKOyZHdlmtsMG/YhRopKGvl9WvTvaMdmUfrfnKG7SZfZe7i3mF1df5qfzm7+bi5tbdLrJ1fXl1fn1zfx8sfd+799QVZtF7/be38EH7mAnan0H0C0D+/4nK3LRoT8x+vg9+gs9gP6DzVPowqec+y+BneUz5F+8L36IXT/0XNtNnszYuTePDo5ez97MDouvXxY/oPOGLkPa+7W+PP/8l+wvKGDvrMhxfGbQf4FFlaFAydMxLJl/wKIpPQJKQh7xsvRmfHYRIpm5Fb6xFp0hZqZeaKYQROFvG2yWIHLX7tbyytfwp3kNhR8cvsSSEhimwd+ODt69fntwdPjq3S8vR6NATegYMPtvX7/94d1baDx+MPi8twisUSaEsxyF4ofD44Pjw7fvBphki+sT9ksT97fxsFI5fA1L5Pj1W34E+M5u2GTBAkHXfowyxJvj16/evTt6fcAJo7gX9HSEbuiYB6+O3h4cHg91TDQUGkX/8O3bVz8cvns7xB0zCOs4dMdBePf6+ACa4ujVSAijq+bh8fHB4Q8H744H+GSGxD2Ks8vk4Q8Ho7C8Pnpz8Prg3avB5RLHLhpp+1b0NAbI6zdvX71+/frN4LaTxDG2jA6Pjl69Pnj9w7vXY/Dg8yGdkZY5fHX49vDVwdsf3oiCMto4h6+P4P+O3xyOQYQ6OwGOs//63eGb46O3h6PMQ4IZ3/m+ef363bs3rwYbyPGtsY0ddJuj49evf/nfvV/+P09bbyE==END_SIMPLICITY_STUDIO_METADATA
