set(SDK_PATH "/home/xwx/xinkeshipei/TuyaOpen/platform/SiWx917/sdks/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.1")
set(PKG_PATH "/home/xwx/.silabs/slt/installs")

add_library(slc_tuyaopen_your_chat_bot OBJECT
    "${SDK_PATH}/../wiseconnect/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/malloc_thread_safety.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/GSPI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/SAI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/SPI.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/aux_reference_volt_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_adc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_dac.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_gpdma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_gspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_i2s.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_opamp.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_qspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_spi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/src/sl_si91x_clock_manager.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_bod.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/rsi_d_cache.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_adc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_bjt_temperature_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_dma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_gspi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_i2c.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_i2s.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_psram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_psram_handle.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_ssi.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_ulp_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_i2c.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/hal/src/sl_si91x_hal_soc_soft_reset.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gap_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gatt_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_ble.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_common_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_common_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_utils.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/src/sl_si91x_ble.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/crypto_utility/src/sl_si91x_crypto_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/gcm/src/sl_si91x_gcm.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/wrap/src/sl_si91x_wrap.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sli_net_si91x_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sli_wifi_memory_manager.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sli_wifi_power_profile.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_basic_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sli_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_for_lwip.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sli_net_common_utility.c"
    "${SDK_PATH}/../wiseconnect/components/sli_si91x_wifi_event_handler/src/sli_si91x_wifi_event_handler.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/src/sli_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/src/sli_wifi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi_command_engine/src/sli_wifi_command_engine.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_cmsis_os2_common.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/service/sl_main/src/rtos/main_retarget.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_init.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_init_memory.c"
    "${SDK_PATH}/platform/service/sl_main/src/sl_main_kernel.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "../autogen/sl_event_handler.c"
    "../main.c"
)

target_include_directories(slc_tuyaopen_your_chat_bot PUBLIC
   "../config"
   "../autogen"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ble/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/board/silabs/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/crypto_utility/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/gcm/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/hal/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc/mqtt/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/crypto/wrap/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi/inc"
    "${SDK_PATH}/../wiseconnect/components/sli_wifi_command_engine/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wiseconnect/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/sl_main/inc"
    "${SDK_PATH}/platform/service/sl_main/src"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_tuyaopen_your_chat_bot PUBLIC
    "SLI_SI91X_ENABLE_IPV6=1"
    "SLI_SI91X_MCU_ENABLE_PSRAM_FEATURE=1"
    "SLI_SI91X_MCU_MOV_ROM_API_TO_FLASH=1"
    "SUPPORT_CPLUSPLUS=1"
    "TKL_MEMORY=MEMORY_FREERTOS_HEAP_PSRAM"
    "TKL_ULP_TIMER_SYSTICK_ENABLE=1"
    "WIFI_INIT_MODE_STA=1"
    "SLI_SI91X_MCU_COMMON_FLASH_MODE=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1"
    "SLI_SI91X_MCU_EXTERNAL_LDO_FOR_PSRAM=1"
    "SL_BOARD_NAME=\"BRD4002A\""
    "SL_BOARD_REV=\"A07\""
    "LFS_THREADSAFE=1"
    "SLI_SI91X_LWIP_HOSTED_NETWORK_STACK=1"
    "SL_TUYAOPEN_BSS_SEGMENT_IN_PSRAM=1"
    "SIWG917M111MGTBA=1"
    "SLI_SI917=1"
    "SLI_SI917B0=1"
    "SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1"
    "SLI_SI91X_ENABLE_BLE=1"
    "SL_SI91X_ENABLE_LITTLE_ENDIAN=1"
    "BSS_SEGMENT_IN_PSRAM=1"
    "SLI_SI91X_MCU_ENABLE_RAM_BASED_EXECUTION=1"
    "__FREERTOS_OS_WISECONNECT=1"
    "I2S_INSTANCE_CONFIG=1"
    "SL_NET_COMPONENT_INCLUDED=1"
    "__STATIC_INLINE=static inline"
    "SLI_SI91X_MCU_PSRAM_APS6404L_SQH=1"
    "SLI_SI91X_MCU_PSRAM_PRESENT=1"
    "SL_SI91X_REQUIRES_INTF_PLL=1"
    "CLOCK_ROMDRIVER_PRESENT=1"
    "ULPSS_CLOCK_ROMDRIVER_PRESENT=1"
    "SL_SI91X_BOARD_INIT=1"
    "SRAM_BASE=0x0cUL"
    "SRAM_SIZE=0x4fc00UL"
    "SLI_CODE_CLASSIFICATION_DISABLE=1"
    "SLI_SI91X_MCU_ENABLE_IPMU_APIS=1"
    "SL_SI91X_SOC_MODE=1"
    "CRC_ROMDRIVER_PRESENT=1"
    "SL_SI91X_D_CACHE_ENABLE=1"
    "GPDMA_ROMDRIVER_PRESENT=1"
    "QSPI_ROMDRIVER_PRESENT=1"
    "SPI_MULTI_SLAVE=1"
    "TIMER_ROMDRIVER_PRESENT=1"
    "SL_SI91X_SI917_RAM_MEM_CONFIG=3"
    "UDMA_ROMDRIVER_PRESENT=1"
    "GSPI_CONFIG=1"
    "GSPI_MULTI_SLAVE=1"
    "SL_SI91X_GSPI_DMA=1"
    "SL_SI91X_I2C_DMA=1"
    "SL_SI91X_I2S=1"
    "SI917=1"
    "SLI_SI91X_ENABLE_OS=1"
    "SLI_SI91X_MCU_INTERFACE=1"
    "TA_DEEP_SLEEP_COMMON_FLASH=1"
    "SL_SI91X_SSI_DMA=1"
    "SSI_CONFIG=1"
    "SSI_DUAL_QUAD_COMPONENT=1"
    "SSI_INSTANCE_CONFIG=1"
    "SL_ULP_TIMER=1"
    "SL_SI91X_DMA=1"
    "SL_SI91X_ULP_UART=1"
    "SL_SI91X_USART_DMA=1"
    "ULP_UART_MODULE=1"
    "SI91X_PLATFORM=1"
    "SI91X_SYSRTC_PRESENT=1"
    "SL_SLEEP_TIMER=1"
    "__WEAK=__attribute__((weak))"
    "PLL_ROMDRIVER_PRESENT=1"
    "TEXT_SEGMENT_IN_PSRAM=1"
    "SL_WIFI_COMPONENT_INCLUDED=1"
    "configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_FREERTOS_KERNEL=freertos_kernel"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
)

target_link_libraries(slc_tuyaopen_your_chat_bot PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "c"
    "m"
    "stdc++"
    "-Wl,--end-group"
)
target_compile_options(slc_tuyaopen_your_chat_bot PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-Wall -Werror>"
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-Wno-unused-parameter -Wno-error=array-bounds -Wno-error=stringop-truncation -Wno-missing-field-initializers>"
    $<$<COMPILE_LANGUAGE:C>:-mfp16-format=ieee>
    $<$<COMPILE_LANGUAGE:C>:-Wno-error=deprecated-declarations>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-Wall -Werror -Wno-error=deprecated-declarations>"
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Wall -Werror>"
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Wno-unused-parameter -Wno-error=array-bounds -Wno-error=stringop-truncation -Wno-missing-field-initializers>"
    $<$<COMPILE_LANGUAGE:CXX>:-mfp16-format=ieee>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-error=deprecated-declarations>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Wall -Werror -Wno-error=deprecated-declarations>"
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc_tuyaopen_your_chat_bot PROPERTY C_STANDARD 17)
set_property(TARGET slc_tuyaopen_your_chat_bot PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_tuyaopen_your_chat_bot PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_tuyaopen_your_chat_bot INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_psram_SoC.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:tuyaopen_your_chat_bot>/tuyaopen_your_chat_bot.map"
    "SHELL:-u _printf_float"
    -Wl,--wrap=main
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz3Lix7l9xqU7dSk5WQ0krP9bXTkoryY7OWpaikbLJjU6xMCRmhhFf5sOyktr/fgHwMQSfAAkQ0GY3sS3NkN3f12gADaAB/Hvv+ubqf85Pb82bq6vbvbd7/77fuzn/dHJ78ddzs/rV/d7b+73F4n7vl73vyneWV3c3p+dL9Nq7P33z3BdfYRQ7gf/+fu9wcXC/9wL6VmA7/gZ9cHf7Yf/N/d6f/njvvwuj4J/QSl6gV/z4rRfY0EVPbJMkfGsYj4+Pi9hxwSpeWIFnxLGxTFLbCRbQCiKIhKK3QxglT0sL/Yvey6Xd7yHRL168WweuDaMXPvDwl1bgr51N/h3+1nFh8V3smrHzw+E3M3VDMwVRYmZPL7ZISxo56BH8+FtjG3jQ+Pb4zfjm+A8w3johdIzb9AlchdA3QBjGRoJ+WwDHeArSyLS2IDFXQWIsVqnj2kbsWkYm2ujTabCC9LzAV4S1proL8qOzdswIbpAzmPZqHqydOrtA+jAxbbgGqZuYX4GbwlgywnaFXfA84PhmnGC7JyB+mMeI3UpbYX6IILy5vVqeSsfW1NRfXR4jEM5ZR2r6+sFt4tCZE1xNHxO4uRuZdrX9UJ2j2HR8J8E/HMwJtktxP9w4dswwcjwQPc0Jtl0tD9S5faFX+zDwGIUKvq3Aym2K+eCqsHSP/mHwODZQ5NPtqnkhq7B4L4LhJm/mho4Vmu2BOaHR6rqg4UHDPKhqmjpt5UIYJo4Ho5mM1aZvoJIkwHpAP/9rJsv1aO0HGsYR8EwQxq+OD47Rh1+2cwLu1d4K/Ob23DyDXx0Lmj8cvpYJsqmpy5KrAER2DjyNQIKGT5Kt16FxEGASBe5c0ApdraBCZ44eg9bSZZ1N6AQZbMmmoRWx1Mt5zNSrNIP5zsgmhdomiECaBBvoV2aIqK8XSBNumRJYPlEjvbAiq9CIfpRANIdo7LAYDaVleVSpNosnG7cgGb4labajANumrNNpUEg0G6qGsj5U8sPDGjK2aNDF+iL8Se71y+B04doS4XVq7OznTgMvDHzoJ3JLtKmqOxLMnzItkAA3kF6erQq70MGv+MEt8G0XRrKRNZSxoZLZuLUpa0WFHl7kSwAOjCUiqisa7kseHTKU9qGVfG/G9oN5vDjA6yDtXUvpHjHVtVDP2CSEq3zfeCJbKqGeaHkG9Y+1RxoPeVbaeKQFcwRbnmo+hyzf+lwTG+69Wh9sPOpcX96hYXOw6Xyh/RU7SLp1ZC9V/CvCMyJPcQK9vBUmATSf64cuSNZB5BlL5+dv6HUDOUNsVNzD2BW+kZWxkRWkQcrKQIVhYFsb2JAGspFRkjdKTkYnVIOVrBN6KRrBOLGeBCl43aRqQQ/v11Sbl5mTgFRvkzqaLhPQFPDqTRpqw6EOh4kEdu0wNnGksU59Sz2NFkDMRGwIQzINY8aBJlQakNrJ9Fadelvr97XkNZPAKAp4wxzBpkB4DQoKU3muQAzN5CnkHqhIQE9jYYJvo0hUF/g0FubaZFlhPkxST6GJZ1TrpgWPGiBmIlQEogeVBiQmMuiNTIV6EhQUVvC6VAoKCit4EMdooKUF+B0Unsqsk/+HbYt2vSSoSFM5hzoaNgrZqqAmNbiOhoOC9zXUBX8OhTs47PuqMQuCWgq2uQLmCLNcEwgUhjmEWGZLGs70ULt/0qR7STdY4UxZ5JWWCyKobiSSmYaMDocASnU9KjdYjMVx8+sj7ji/I4gcPHVYLtQoM3e2UJYP/brRjXLMlug8jccmNwgn3QGpgyljQWrAqRtZG7XOIuz+ojYPHTk4t59p6teLndjMXmCrW6eXy4sl6yTwWZ/glucvfMtN7fZJ69ZyzxTgNSVFwXRua6NqSIPYyMiwGTknowGVed43f/ODC+Lts+BYIuWleHF0+iwI5jh56S1PLp4FvRwnN73rZ0LvehS9u+XJze2zIFgilbMKwx5jfMSmVhBJtVqsAMMQTnzUyZU/9vrrM+gOGXs+iolOPUFva0+h1qmB723EadQaOTu7r9+dXZ5oA7sAw4Jbq25koKtoeLcujXmOhdG7tUHN3AMRh9IFdgGG2bu1AV6g4RpnN4alqe+sHWjj5BbBE1B0PrRKu1U40nN9JTK2SXE6wTvLD9SXVwUge4KIaQFrqxWpGiy+kgK2kjSXwQLKcfGRWf0zMRPohTACSRpBM4Z+HPAmw87DrxsqH2XbA1ryy3FxksnGCnj/ip6kaHx85PCueS1ZFcD46DhHejYcOS5eMkrSahnI9ObTdm6c1pJMjouPDN5/TbbEakmJQsdJLAZRoiepAtmMiaa1gFPhALlqFiojoEQ2IRTWllcFIHcorBGpGiz+UFgjLnVcQkJhHfl1Q+UPhXXkl+MaHwprSYrGx0pOX1ojCVVCaL340MD4Y3sd2eS4+GN7Pcmwb6agYmgdyeS4xsb2OlKi0I2J7bUkVSCTmKwZBR5XUhnXbjQs3HIflFbpHcEy6KzCYg6gyUuR0qa2i0rEt7EIvwNVd+odXCBXl168tQkVh5MdbEpc7BtegPXg+EpSYXu4VFDx1Rel7WpXdeHbgkS8cp3GSofOXbWlwMXFZu0onbPp4JKj4mISBo9oFBCDrzoWDg2Oj9ejjiWUo+Ji8kXxWKuDyheekVbxUqRdu1xBxcUkASsXmjfLw2/oPw05NfCNYKdsyyUTN74tmOW7qsdfXZy4Rl7FW6meQVvKG7MVL5Gz6kMtC6gOj4+bG8YxHjDpSKyKTeIwGdnNCbcwAsXcY/uerWn7GxWn9zQ5lhlLPAk+IP1mRnANI+hb0PwauInCjZoD3HqxMrG13MB6MNPQBonSPLMOgnV47KfBRLr6Yo6MfeUT6MokR8bMBKrOterhArnyrPAb2eSInmxKbOxsFCeM9ZHhSRnDLyhOsOqhwpNihZ8PQuCFmnIpsTGz+aKvj33h9TF9qXAzeYqjRNcuZgeOmQ8ZzOnaAOzAMfNJ9e1mUt5ehhrH6cupCpGdm+ocyz5SCrIsi3GXwkF3i0WKwTdPnlv3KEs/br1Y+UeE+hGsw+MaEepHp4KMa0SoJ5McGeeIUE8u/Ev5ypfxe9jwL+WrTjPsI8O7/IXVgggkapOS+5oACiA7L6UJCn18+JIUlCco9LUD3EkKijNae7jw5LQW8xW6MuFLf8tmK/TkUmJjT7NSm2DRw4U3yeIL1LWTyZHxzW5pSoW3v8Qv4EtXEl2DMxog+3Kw2hSYHkLcaTAax5oRd6wZazsKiDnHAPo2ArxtQKwxFW4u2TSypmxKcJx8zC0ENp5O1plXFSTvHL6evHbg+Obw9WTDnS6mS6rYAKdR6WLK91L1kerfTdW1Pcw7NkMda1IToMT0txhGGCRbzls2w+wBH2x6ThTnSJTrKhpKkcqVo9w8BgWIPqejgbXTC4duVWReTWIzm0LPbjcb5dwNrKPMxnUHCL69j3RRkly3lG9uQbkjV3kOQVEWO3il//YDVuDHTg2TDj5csVvmwG0gRTsv/7mY0vOYdyfV7DSpTlvsJl87Z7IJmfP4oJ0ATU5c46Dcexab5HOkaobXYDP+UNTVApnzFJJnQnQ8O4UXJ44hyXu5YlcdegZ0m4hljh3IpYMu/ApdCXtmVoGtNGzakSuTxXJI7IuEoZfqxqHAxL6i5rq6ccghsVPYbdjWjQmFjH2NQ/GQooUJdzIy9EINToZuo1KDxjU3S1pg/VquGjT2ab9yF6ZmhChgzHQeH22lichtTApMMycg475M5ei6YoliHjeHxJ7tGavfN9/Go4qLL1bQjEiBiStW0IxDDomdgn7FwF0KWhye08pk3Mk5YRRYMEbdsQbn57bSasHHHsvBjerciDZOFVgcVBKkz1E7M9BOpgKMK8rWjQhnOkQ1lNWMSg3aqChbN0o0tBFRtmaEGA5h6YqyNWNSYBI3HcZ6E/gWtM+OMc+Ntc9NkhW7wEJ/1glq32KoZGCDUNDLDu2wpl391j2uYTaNAm/EpqHmZtthcZmm44uuj2kzPjoRdFGY0mLL2pMrtz0hZJzLkqGdC80NCPFJyLNvQC94GwjEbiq3BqijXWjnkSS6EakgYmWS5MsiGlFpQGLnspr/hsMuDqu+uwzbNuBpVQjjSiBNHFcP/CUSBuS7u0808J46mFn6zKIFIcU9cydJWaCcA6yA4WiTc69Vc/hAJ5EGKnZGunDgQU0331oQaEDi5qKTS7WA4uWjFxEOBrq51ji/0qgQuEsgjedfamlFXgDhik20AF4g4Y1NVIOvgxExaG2ELB70guipY+BZsYwHXBcNo1fpeq3gOLPSNhlco4mmaRxWC1jRU5gELENv3imRTLIyP8rU1zYAlJCmRbqZHFK3nKTdfQQkPdNalDldbkgaTW0/SgOpisTfGgrFjlezV4sfVpFKTJncWJ4sD0WiVbslglC70zzDpMIBsWrFXofNQScjWz1HgAjxL7y1U5aDYdmqPQxjoF2sQKXCx4huxU5GLEJ5WYFq/qWutRN5jyCCZhpuImB3LSJUTFl7A6hIHigtWodf/wD0ZRAM01JVddhoTQpcuxqTxva+R2ddZAGFUYC/VWaWrBXpgjRYxOWr2ThA1WbldjpNTAx8qCulFfNoYGHBXwyxVQboOfwalAk1yzV9mAhNIHCwxOIiWtXmIvRK520FxjZZsnvVQiPyFbAezHWEvn0MotmT19vpDUJkJ6qFpze4DTp9f7k5fgJRf4R7I3MLfNtV2Qp1FFwHxpnyW7IKonpMndum2AxfgySi1LVgNoyRk6putKRN5G6DODE9K2XqtTASJu93HrEVSAaVb4UmVqKseSgY5p93YZNiXbBdEYeM1qDj3J7xaVo4RQ3RwicPoY5JmXkpimVmRxMcWwUscGlEp4aKj4dZCNaTEAWPa6Er1YwRBYuJCT4Vs2wKtCLTQMa4eFqtdIFOVagdHI+/ZXv09GHUBDZbCpjitATaFqMTFGyQADN5CqG61f52JjQwVjbZ3IdmTEpQjCy8Y80YZIAY0Qe6eVLA40HhAwpSN97sux8GOFRhPYfUo3YWnElIWDHuqrYgssncewyTVN3iUTunbpCsLF3ga5I42cGwFSAPOxuuHV+7HqYObUS0qg+hFmScfJQcC8HIaOBoiHqsmmnSiksFk5QZjq7AtW+9R5V9covUoLCvtiF9cQKQGtUMWuDwsMCryYS/o7BtrFGpY+JeA9WCR3/I3bEDFs9PltVWDx5NTOx8nCDBPcHD/Dt527nQeNh5kHt5rMBVPEqlj4xsYGLng+8a0qwFa0DiYJOAJNWFRomFHb9GTsXlSyRlRXGck6OvQWHO22j9uOXDxkfND+hYqKidVEDU2Ni/dmoBE8MSUGsprEDsWKYVQRuflwPk7uktuBlYdTEF2g2jXhitBOZN/uhmwJbh0Z5Rpp5DLxBjyMmZAvr20quUuMSWgKZcrfo1AGNdTg32VhyjXW5mDr1A2MphjkCkx/x9QUcr4Pmi9G7Uw1F5K3TpoUY34s7Qog2oEohNcCyNZHsmTCup+XqDLL1lp3aQFneA03YBVe0RHya4Iei4eGpEqINToGaKcYpbZGocqpmFnGEOfiWLj/J0ddX4m2DYKVgwSpBrWSCBaMgTRFK3AzBzaUXFQEoteKYAkzhctv4xQwJxP+guNCzugyCY7qMjdUMag79UYciJizMTzRDZdLGtpI1yhTj4BdtXDTlHwALWCeWHNQyIqzBYYOuAmQvwPAEkA2q+cNKXO/k8jJdpNNfSoioD3YWGkYTyNq8FCBN0xb7t8FfJshtTWyGrMMSPNDJH7BtoNMcObQfPJNsIAtuMwRrKjZ4ywCTc6FJtdKNFNp0hwqtgpBUafUXFEAnVuQDbdvAGHHyIrvR1mpxV7pqtqvstb3mxE8/RAtNIG2oHUM7RxtYQdremdXQOhPDNwZH85pRG2FA7gHKGqLEGsDNA7Kr/s0Hr8DzupnoVgMjubanJIt7EmaDsziGkSWYDSRSUi47lRYK5Vgljxp18icVOsdrd35Rr7Q05yifzBMw0kn7qRzfaJoahcMk5shSYt654CGX46KlBSSkeQhk7gRqUlOJBlORGdEVAa7qHsH6BKip/XfEQyig+fvNSDc6a6iGkQQi8UA3SmmoJKy8kKZmcGIUnQuBXBKXY3j5hlNQnVupsbY/eyibIbmCTIpZiAXui4WQv7xU6qDyPwYFkvjY/x4JBGz6Jw0pnxtSBkhud8MA8IHLmmjltxck25HCkr7q3omO13RxToq3WYx2Stx5HNjvahnoWzLUzx2YH3dQvpEEn89eokzChv3H83jwFxva9JnGO5rSmspbl14Ajp5GlO9wZ/KPOmnKXBhoWH6+ZSjWHJhwel6d+pX+pT7Z4oetYqP0yEWTz6ODo5eLV4rAs9HrKcs6z4hTcM/EM88FJ4Dlidi3S/HYP1WaBS4X9k24rR8w6IRuqXBvLbHQQH4k86IENX5vqgZq2ewV+S8wExA/4MlonTgS1GkzAB2EMzazb0LRcEMdZHpGoCS5Go7drH7K7Ssyd6vvtjJ6G0Zz1badwyAHmrmhs1Qs/FzqiOmBmaKXKIXCRmF6VFVg0HN6acRI5vpiDDNhg7RQOAHNRazQnrkLfkL2ELc+y2qttUXY4cB2M15u9l4hYfYBUvpTepnpCxzkb8EEYTA36fHbeKRxumvBfCfwm5hg0RjeoqWVqquaDt1M4AOwpxjt7xKSqM0KrqGRpR2dEVuibNEFxerm8WPaNoU6R6/SvkF/4lpu2XNNAGSirzrOEDYSSgXEbOTSjqb13ySZ7HN8CLzt67cRaUd4LNfkXnvtF9VpuF96Ck9bMYM+NJXeg3WnLXHE/RNJCCjpnjgdhRW8vQC9MTRB5X1/PjZBSzL9+2Ggubm6vlkfCWhQUIMxgEIK55lW55t5CC2IzcSwxu2B5EFb08ucGLYM0ajkTuk4M9YxEh8wer8otg2XQmsWvZ0PPdVYTJhWhN8d0AkFJRi6Uvp4IBT23kjyeokCtBhNc0UMzzG9QoJimN9BzEfDWqS+3u6KAVRT2I5sjKKGQdQYizbKUPOtSK8nBSZf8KXMDfRhJnuRvYKtqnbaCOLyzGQ0GPOD4Y/JYqUeiJKgnwzaMihWhgXgCoo2gnapdJi12euTssqxXhNBoQGh0wR2n69QGbESO4zvz06grH8ofIw8/wMiHrjKsO/WDu5eqz8usdO1wG/qZrIuLIl/8V+oOFQxsdq6+pMzYNRBy9jDvqsycPPPZYUo5T31VhXWC/6s0L48XMczNuxCG5Kjc6cd97GTN1EAU6nYTflUAg63D7nF8w8VMhVrD3IZCTuNQMc7MTMtlrSoAjtJRg7eOYPJAuv4rXYQ4c7E7kyfZOpFthiBKnvri3HUEYUuMWnsqa/iGYl2nY4qpVlTy8oOwRYwKcaNgZ2QEjByh0ZUx1MBqRQESKiihbCzaKogBvDYMI4hPx7GzM+fJ7lgpMxTM6LshDXDJ8gA3iHyolkEdyADuD0gMnl5TirkKYgCvrFwFZqztyQsNnB6MY7CB5ipdr+U08cyIm1CGsIdpdpyzuD0Co7E3oDBgz5dsTT/1VjBST6AFDwOLxwiEoQ7wq0AGcIdBlICVoL0GYzFXQQzhjYJ/onZerY2rIAbwfklhqta4JYIBpDH0wq3adm8HYQhrgk+K9QAKXdR6Qh3IAO4lfvxSPewajkFrRxB4OnSMDSQDyHEOmlLABYAhnHhMp9YldhCY5+bpzR95G946PKOevITeJfA3wzf9bCEIzWMZUzeDVinYGDlYY4eF+WqABvGPp6cs1zaf3Fyap5fHH1ju8MQ41RoIkTIKxEYBp+3yhxbkpN1U4vXd8EtMbRx4b7hiWdYqh98qirGqvHcCjBqkqkBaB9CLVlZe5yDKtgTPBrosIlMBr9TcP9lJ9bIqcDYQ9CdUok5WjVOWmvvxZV2rEoClav45fJIzNzQp25F51pn4N6sRiNoiC43CMC7G6UpyrLEt9MvKdBwiXKQU1nEMBKHl414YBFJWn7iBl0iYymvqEkhtK3QthYbTdUEYxkaCflsAx3hCLmhaW5CYqyAxFqvUcW0jdi2jEJzxe0cdSlYoP4NrkLoJ0u6CFXSpT8gpQaeBF6I3VuSkCdx+5xeOAnKjlfngJODtwQL/7+Tg4MUqso8PDo52H71GcnBxtIjZIDHe4eGht0lWAD2WoOJANBy//iz6DhVw/VMr8BbZ2UYL9O2CDJbRB+jnt8Ve8oW5f/jy4PWrHw6PXlY2lnuBDd23NoytyAmxMf74zmh+lhUaZTT02TsyPwOtBP28993e8uLy+tPF6cXt383l7d3ZxZV5eXV29+l8ufd27x//vt/DhYFCoPNvxPdQg/f2H//73f1eBL3gK7TRr2vgxvC78sGsOSHPYYZYdzkdflreLPxd+d3N7bl5Ri4WM5E16e9Cp3ob8e5zvL+7/ZS69meSKKsm1Lf5DqJW6ZuwehAa9RVZ10dFFeVbuDokkDPWMz80vwI3zeZ6qUfyayw90CUje2CT3dxXu5q5+8GeJ5yjePgBkrOAfjjofzSMIxSCgDB+dXxwjD78smV5vqdE8/v98EXokeOB6ImJNP38wIPkRAmbR3T1jYFHUzfkRk6/0/cwmUiLnX91umz2HBaYYt9kQVB5uOcpPFve+cQuF6LjCXIeB97miMDYq8pTuBFBTVaKp0Te3u+9yxult5eX5MMX3zzXj9/mn76/v7/f2yZJ+NYwHh8fi1YTkTTi2LjOHlpAXKXxky/ytoi8lkRp9qFjk99Ta5HpXWS3uKdW3izh3ihAfZNJdUeLjWWR10Pbo+T98Z60r2SCCOcTx6iXSBIUV5KnFv+N/zbwQ2WDW3D7I7FRjhGxxxJ/+W5qWwvSJNignhU3qKflgSl5gRRfurgvjnAHnVfIZXC6cG3qmXxnOnnftEAC3GBTE4MeaRwT1/d14+2socEHfFmwjhH7Vdze5NUeoSRo5FC30MMBH/y1uBT6s0AKQ3z9D/5OG1PnKi5hAmzkqM/d3kW4+13n2UKce0InCco3GU6SUdlrMVZOZTvhSBHUfr+RMui9oexCevbZjRVS2QrHK6J1xxmLkK7DXka8WyZ/8b+bH+rE/2LbaUsjpLSfxDNG0BQQfNW7/WQX/jfLQ05GvFqeQzLm3eLMF+53B4+qGiNxsgs0jtfgf7ftCJQRUmonaPBLKM9rGPFqeT7GiHcrB1hwvz14DAuLxI69qtyvrthrRcemzxGvsjcAvVsAuQVUNoRyv8sZRrDseBEhp7K1Y6q43eaWMZK6dxKOlVbf0CdCTmUn2FRxu7174yW17/SaLG9sSfZvv5gkq741YqSw1l07k2S17abpETh+gUSk0OHwfcyS2yhxLWkKU+TUkwimyGpLhRchr5abJ0Ik05Bk1H4REfK6d3CIkF7fXSFCJsNIYUKuvxCpjSx8UVJbUuNFia6mrYuQWU0rFyKvkvYtQl6ZmS1C2C53Woi0Wl6zGJm15F0RQosEWyGyyhTYKdIYxowTsyvlSC4TH4WIb+bNThFb5q1NEdJIKpsirMz8miSkzM5CUir3AXxP5Bzj/Az2u/cmimhNNRghMK5dWDdaSu0arNFyqIvpRkuhrjkbLaV2CdloOXEte2OklNodc/yCGtdaMolguGR3hJzGFbhjZFTvZBrxfuMK2TEywkmvjzRA313TvHJi6j5oprdtmI2fc7fCeRmGZ6Vkccywtk5I6K1ADDmNwyYYr61KEVyfPhUol5ojFSg3e1CwXNxIWFYoBzQWDqMoiCTIDWsJZYJl4wyVyqSxSOl4AZS4iQT0eWafDE/JRHtfQ9FyM3OQrwWKxu2dc315h0fbm+wnO0jQZ6GXmiB02KO78boapU0STcXqxTpsCEMynWnGgSVBfrU+iJVO0lnTMC99wbKrjiVGNL1ATCpEIKpnolcaK7mXwQrn/6BCtlwQQVFMSJpk0fqncT2PUpx8Hz2GU02DyME5XDLUFH7aoWqqxezIwcuA+ax59lue3HKW/VLM1Ge/4iRIEZ0pt94PLoi386u9ODqdX+ny5EKB0msFSu+WJze3ctTO4K8fsc2k1MCP0kpDmkNjp5ViC2m1QVrpSSu8u7PLEzmQiWQ5mEkVlwNaaOsRwsgJtzACrll8hKMhkH4zI7iGEfQtaH4N3ERUNz+g2HIDFCGloY1z3iXrwhEGsKePCBnUYCkgAomAkTOLtmgeUtPnWhi02GAWMnCNYuZZFOEdgXMo2oS2B2ZRFIfOHHqco1k8wTmaPgJkUENWXeZQFD56c6j5Amdxgi8zORvWkyV2zKEt8qX3rETNXE1CPE8TN5MvxHPpIcuE82kytxDYu0QMqRqplA+pmtKZfBzrKTKpZtEXAwGrWwOKyqlK79gMpRYXnuPrHmaIGjp1KKaGGZJ1FcOMGdTgwH8GNTgkn0FNFinPoCiLlOdQhDuSGfTgEHYGNVkIO4OiLzPZbS41WT8/gybOvLcJmtKZqhDV686hj/S6ohRFgVfM45XDM2A9OALD/xYV+CPLfRDXnXfpEDjv1KVCXATUoUHsRFCXEqGTQB1K1o64gX+HCrFzTB1KwuARRmYMvkovFpFTJR0qhM5fdOgQOZvQoYLknps3y8Nv6L95lIlJKBpSVdnYKE2J0BFqjw7ho9MuXW4Yx7iHEaao2OaZjdM84INNZTsrGaBSX0lWTCXx0IpFRQZMO24rG1ulaGxsy8UKi9wlsUFrlszlwq/ZtqA8uZ09O36MfDsWXL/blOB8RKkKQlegD7TJl41ffHfeqiYKLBjHAVIF/VjgwmubsghuhE5Gt+tI0Ls8W4ZGaRE4Ad0mH30QzlEiuKKbeFwnuU2R0Pe1aHl8tMUNfKoKdvuK2HcVjZFPWkWZCnCrKFX+rtWSqUZWF1tOCFWqn1Q9leonU8+u+snUQqqfKAWp76wdaOM9C7vIxLSAtRXXIdZ1xMXElil04qFFTRYsikyr6lSy+mdC/BlGIEkjKLpX6dQrcvTWrWTO4hKawdOpRWT+To8ScdOcnUrIgcczqclPPpavLY5n8AF8ULjYMVi3KqHr5VU15Tpo3mrL6BmoKQeRy8edSjqaU+l6RS4cdSupNKfSlQld5u3UgpvTGZSIWz3sVJI1p/OoKZpT6dpwcypdya45la9K6EJooWYoDUlK/MOiVNQGel7dle+VcK98LyNe61hp76Q/g7916RfRvm6BS5uXzKcHFvqzTswIxnB6hIJ1UBxadEzh8ehE0IVxbIDtynT8BEZrgJ6pbG2ZWk8GNAg6M2RIC3EHmRrKmwekSJ+4b31AeviQmN7Gm+atAzrwpnWZ8rFQVGFQ/YjsR0AiXHzzh0yNLvBbb5+Rp40c7CmvpuCJJPKGPAV490B2rR4+/GIGNdPHox2KinEibpCx43nH5tRAl0NTIE0TPustP5B5BhVm8ZhEXfkIOJWvY3q03quFrjxC1OBDJssV+okTUV1CswN8pEiW0PxSKhKhEVCraFnWab/bT6AGWZaRahZxYQglNXFcwWB37ZbIWlmuCKO6swHh9KO1eqQniSzxCTGKDLlV3xMuX6rwzAWFiqVcUIhkK3oKkyD/pzjdspb5R30nxvPb1dJ5f7RakWw3llebgbKmLS+1KaCnqC1BoVuuoKWAhBLAmay0EvyJeBWUkYgKIVZaO5FHhpxpuIkAvgKE/iA7CnpGVUIMtw3iBA838s8rkafpW6GJvxbDKS/4ohETVutpr+U+kphHNrY/ge6IGpy3pAtIEEzKuBxlSFDgBAn2mIeJM6HtwskBDlbgipw+pBfNs4vSpTkO50Hd7ILFG4Tczy1ycii7Sas4LDu7TUBQ/ILg+jApkKMfBewuGRJOatEmO/W/dp21SIUO0Si0mczl530jFl9tiUUWSEVF3nCiwl/hQ1PXEfDgYxBNS/Qb1NdWRuIVOhWNYs0YNTpKkXKpvkagYCdrPLIKL2RrTbuCLIkXdQr42npm+UUnYmAZ1daOuXZ1SmjzbwFCuTukHlkRtPG2A8Axe9EtbWQ00S2Qrxtrk+MILog8Fs49ZJyP5dWNAFuB2LGoYpguc0Kr2ia024SsUou9aKhZxO/Vd/z5HMHhsKgR9YNBqO0LFbcOItN9dNiHuAwyuS88YZApXOCIat0v1cnLnMys8cZFbKLFupMj0LC7AGdyXazESnmbBKMku7sconFKwHGUPbOKvKtmb/MYJI9pShnElhVWjMxWr2UWTdYByRQWrk3ZzZx5OFtZKGx/gEtLoyNl99i2t8fUpVY5tVBymjA6bJwmi7Nat8rgbsQKKdXumr+Yqc5+jEvmJeyhUrFN6G8cH9ZLv/odN79e2bSPTxVNBz40bGSS/0XCvcBOXXi/9/Z+7x2+0BQpeXt5ST588c1z/fht/un7+/v7vW2ShG8N4/HxcZENZBZIqoEGMNfZQwuI5xDxky9WqeMmjk9eS6I0+9Cxye+ptcj0LrLkppLKkvyapE8gCKFvPgVpZFpbgBraIFlsLIsICW2PkvrH+3v/xYt3Dr6/IMZ3Bb8IQYKC90z34r/x3wZ+6J1RY/hHYt8cKbIBlvjLd/8uPzr/Rq5EiNFX/8DGilB9/Qpt9Osatctw9252wXX5nBZGteEapC42KXpjE/9mVSFWPSV9XS7jGg0Uf0Qv278ZV4hxf11mvd8DaRJsoG8sYtcik+TQWFiRVR4fGunUCKdW8b5aq//v3nd7y4vL608Xpxe3fzeXt3dnF1fm9dnlcu/t3rs/IXvc37/AOfFI1fv7vcPFwf0e+gT6VmCjhg59dHf7Yf/N/d6fkE6kNNeJHvHRgP99G/HTrDx6eGMNSFCIBhNPSwv9i+QUgveIHvQA+v+7deDaMNopy4qaeqZ4EoVpu+eozTIpiKpXWaCnkBfhHW8QFV1md/yh6/gP5BPig5mRuZXUUqtE6iJhRwQ3eJraXklSQmY1sq7O/ArcNItbRWrwgOOb5Mo4E1/zLIPHhwjCm9ur5anEMsd5AlKdapMvM8pWINFj8+WVo9h0fCfBPxxI1RSTI4AcD6BR4Hx6pBsQqyNjFnsOYlVNs1DDredcpUbrmsX1ZcrH5/3JkU+SVyRB3500J7W4yb2bsfMvaTyybBOywRiE8avjg2P04ZetDHU3t+fmGVnyJLfPCmZCLpjPYadRmSwmRUUSBa5Q4aEjqw6TLcEEuEzXmY7/nZGFydWPnOz6yWuQbNGvaeRgxUlqO8HbYthgFMF0JqscTpDfXsgZGtxCD2/xgVIGB/n4kGl0kAUleNrZKkPccni3M3uzLJiKFx9+JlN4W9clRgHxswh/lrvnMjhduLZADbgpOy0nW0Vbp5z7NC2QADcQax2koDGlLE+4NU742OagrD6ztQf5A5cwwSnKQG2jgB5a5BocPOP06zY9+xrBaMu3L7S0FkRjlqdoHlqe7ngnSwjrfL7jrWzGb+CtzndRJ870aocAz0o5Xu+0VTTEml3W1glHyuqyEZ6TnSCwQ6xzfXmH12bbZgJFqrCDRAR+WhHV6uRXwyTQy3tzEt9ntS5rK/Dzb41t4EHj2+M34xvuoGNUUNAxblGtvUK11ii2TRtL52e8HcNA1S02KhWQ5UwR7EkGdgGy0Fma2CgtYXSCbfZtAk2Ej5Etd8fpaBYKoChTtHQlqgXVwpXMEbIceg1Kpo5nekHUCeM56zTUiHEdkHDK5BSYGB9gYa5T39KBdAskKbRtCEMyU1UcqqAD8QaoKdQFNAzNXtMX0983igNGUVAMt5QVQ7GvvwQj3PNWIIa7dDHVXGk0wsnSZ3ypJkujkdKmWFZYOR5DNeEmIun9hyasa5Ck0KbiZF2IN0AJp46k77aDqqZMgZFBVZ/KTIGRQRXEMcyO1taA6g6MrCZLr3pLARI/sKmOnDRgXMcjnnC2eK5NO1XHI4mw9zXUh20ORtkAZtrLLTPWqO0VO3cqZSxVLj4HSoNuYi76cIpgctwtY0AragK7L0clWOHFFFT/LRdkG+rUFgt9pH0HxF9Nxe1IKNbNZ3AY4H8l2yOdICJHCpWJ7wodBgMop6e68Smv1q1jcXzqowaRXmbEDlCTLMfsQlqw78Y2zggjHWfsa40V6eyuAWGLs17sxPk5LGLbq9PL5cVSxjLt2XSwvfIvstQKuSu0GQnzVOFQv7i1ouoCBik1I0Nn5JYwGmClrszm2j64IN4+E8uUWOcwzMXR6TMxS450DqMsTy6eiVFypLMY5frZGOV6NqPcLU9ubp+JWUqsv8b8D/ER+EfsRkrGLa0lW8ARGGx/1KtKfxRQb59JYCQ0Bqpx1qtHF9Br1/jp1TkL6IDr/LSqlOLr5N3Z5YlGBAs4IhlqFhQI6fhbaqE+nWOORnAt1Iif8L6fuL0+BAs4wmuhRhQLPLPOFBamqU1LVa7TfQYLC80bmdWV6fBt0eKXxrtuitbVChWIchKfdxfc62OCGjB5XgBsRcneg4WfI5NHffXPxEygF+L9jSm5KdWPg0hTa3SDlWcg2wOaWiNHJpF6NqYurufW0QQ0QnmmwMcmaWqDApo88vn96Bpyz5HJpK5oAyIDdUE7D3tOTtKUeo5MHnV8YFR5fa+GBqDwSTRDDKJEVxMU2JQnGc2awJkNiZROhFWLhL6CrcA203BNYytUIEodrmllghowucM1rZjXkc0+XNPTGt1g5Q7X9LRGjmye4ZqmJqARyjCFzkaYgX5lSKgbexqa3NGqntxzZHJHq7pSl7PBnhoT6kk9RzbHaFVPA1D4ZI9WNTVBge1XsoEqCjwpmxKknSSDAVvug+LmcWe2csBUBSZlqEgURIq7xC7ikbyjOLB8qD4M7GAOpQWBhYZNqHwo1MG9RCbnGAdgPTi+os1tPcwruOTVc8X9X1c1l3doB6lL6zRWPBXWVcsLZNK4rx3Fs8EdzHNc0nhnF3XG4KueBU/Dk2eFRz1LP8cljfcX5fMbHcS/yJrdKBREGvZsFVzSeCdg5ULzZnn4Df2npQUaCCXbQuHBTUyWkHeQU6lH/ZxHlwWkzXYUGlJdg/tUZmxfKCD38IWaFn4doDxLuGEc48kDPc1QRfcrmfZCJeqEWxiBYi1n7DkfHfKlnSGkPMG5abkyw1tWijNIv5kRXMMI+hY0vwZuovTopAFL9KIVbhvLDawHMw1tfCuXjuaoA5RzMnOkb63IscnJHgL68s6xSeEN1Wey9zCH0rLYsfRs0lVX7iU6OdyVJ+/3UZeVvo+FK09f7yEuK4Edyw5C4IXaMi/RSeH+RWdv/yLT23UmLpX3Uxwl+nbpO3hS2JPJFn2buR08KexTnbv1VGavTs2z6GyBKkg5llC/T6fPBP9RO3WKGQ2lU3ItpVFMzcnaodA9f6GjJXrRyp1t0dEcdYDSZlt0JF/BJm22RVfeOTaJsy26MpebgKdB8l0Pd7kJeOo3n/RRl5mggSGCCCSqN+T1NXQURDlWUJyE2MdeXiKiBkmIfa2d1ERE5TuuepjL2nNVzGDqy1veloJs/lJX5iU6OenlqlMue5jLTLv8AvXt1HNs8mbTtSUuM5rBws0wChJ9g3gaopxEK9UJtz30pSbdaj2CiaSOYGKNx62xxFGrzk2dzJYu1pq4VObZ0py23Et4EtmbWwhsvESntxWqMGWuo+pqhR08eeuounKXmlSvT0L9gAWkJ9VrcIJEnwlEnCHRyr08psI7NkM9W4AmxF/JloIYRtggYvcRZOt5HvDBRshNnJI2KvQ7I0VCbXZDXkgGBYk+j7SBVkAtFXYZnJzMB57iU9qmtBcf1aw00GpRfFLutnchDEkw9QwbhhK7uQXl+VoaZD8WHrYDWLYO/ZC1cLOOspTaSjg1y+jRQlTKL2se2mBqUWYahTDFqWfPcnfk7tzmHXr124S6TVq7G6gJWuLh2ztl2twIwWEgAXdFPJss1E4H0eJ4xKExXgtoiWflPhuzzGMLnCKk/GpfHpNUAM/W9j0L4zQx/1rmTJ7iBHou/ArdZxBh4Lm7VWArHqDsTFZuzMhByUmNCr1UP8YFKjmZQa6rH+MclBzCu0Pu9ONNYZOTIaF80qGFt9SNltALtbgfso14DZy0FVLSq+rYmtfAyVkgK8900o4+BU0K+cdHW/EmyzbeBar/iGFtEbWonSuslEKxNpuDkrN/LNbhpMM21lVk8qJI7WgXqKRFkdoxzkHJIaxjEUstYU2Orm7lLf/c6jAKLBijME2Lu+tajdCCUM4IAm7U59y2WaACTBLxBGFzVM8ytlOvQJM2btSPtsQ02+rQTDviNXDSx436GYAGJ3ncqB19YccUd5InIzTteBeontuSwNjX6uPTLRi7diB81aBrzYnkCwUW+rNOUL8UQ0XTDwgHvajeDmycJ4ldGZo668BRFEpqNC4Kao2vHdisRcH9Gv8L9WJ+dCLoohCdu6wbklbu2NRr2c0AmVZyobkBIb5PUsEBh4WVDQRjt2hYgzSp/+hinCT6Ua5gEs05yVMYtCLdACWeNdKnD9scjGCW+hWs3FJNE8fVhWmJRSDHsuPVw3frcH6FMVjRAhOHnT3ooixervZU4Ejo//Iaqur4zE7KDVziuevDVgY/ukvVhGoDlDTWejl0CyxZzHWjLIGrfo4t16u1KlhppZrGKtIOWjkWUKTEq5pQLLDIilfV06zD0XuiqrBoLcD1oBdET6Onjajy8YDrBpa5StdrJZdYlCWUkTKaeHiLSJSVregpTAJRk3OyJoYzlAprVgagtpm9BKXDeDBDQ1o3JxlbbTpky90SSiNXWDnzQqbx1M6faGD9j8gI7eKvvELWyqqlflaxPrdV2I4i3ljec6rfCK76So1A0DU5R/WfVX0xaeV1FhcFvb3Umnygska1Ex+f9pyqJ8arvn5iFHQFLXD9Z9VQwlp5FSWlQdXRAtdzq6SixklrJ/IeQQTNNNxEwB6fzkAVe00qUJOsW5Z+nWT9AzAtY5eFvLqGiI28wqH6+G6g5VioR2dd7EMIowB/r9D0WbvfBUqIs5XisxkYdQcetpNuohLEOm++sxxV5WwbaESxLCZ21U4g5CRrYJS1F67pw0TTvDvs+Qhd7hAaFB0xVlkpW6GJXTDYqbCA666A9WCuI/TtYxAp2PjdbohBkOJNoklNblhhYqVm9QXHTyCKNnCsYW6Bb7tqW+0OZ+hAqcM8uPAliKwxUD/jmZdFcWBmDdSc/qiJDYZRSjKKfgZ4tou82yBOTM9KhUUp2BpC67/ziEuM7P7wrdDEgBU2yIW98s+70D1LXwDbFanI0RqMPql/ju0ieDMQKgJ8RwIKhRQ6A2WwMh+7CU9sM1jg14p4DZccxmYBQFfqFEAp6U2pdtwpYEI541vgyuZVM9oNbIIT9qqNSKBXVW+HJ8Pbs1OXdOLehPYrHHJpkfhL2156CrANEmAmTyFUmSXbzpmGJpp3NhOsHecSlmC+3rF2XDNIgnkG+vlxIMN/wwc0HNt4Cs4pGGBbBfbr2q7QzlfSxgUMEAcaWxDZZC04hkmqMkGjnX03TNH2cIGvzUazDlu0QpRhBxuuHV/DHrsOTuKoSCfqLdgkMVd0UCwjdyGHxTbHRBkizVhXUD3LOc/xQ6f+HAh1pZSXSw2M2GwWhClOAIKinmcLINFccQYasaSjtK+pEa6jkpKvpAnbqcPBzvPO8GpO2aTpwraJSixrJ0hw//yg4nS3dsY0IrFswyhIAitwlc/u0JdWNVCJZR2Hjn6tdAOUYM4JSFJ9yJZoxLLUyo2Fey9JxlUe6eYca2Ck55FyvMD06MBDQ1/XY+WizRoImFuOsVw7TEH2xOSBDm9agdixTCuCNj7xHMg+t62wkoGVF4tG3UDYnaqD3tzJq938pmaodu0Y0IFhLxQWijx1e9ogtctPKn4ntWWlzVdtSmsQZLi+KmatSKS4/uwMe6FML8N5gtSeohsXkHbQmXNE2c1pygiyg9gMYWc3nxFhZjsNRQRYoU/pJHgzbzsMNGfPmqXQ7hQLM5HgwDeGER4D8Ma9PkxwM1lsKlQTAuMU9dli39xQRo15df+KwPAXi8ti6nyzqnp2TThiCFowSlAlsUACzTgJIsmbhZmZtuKaSFk1tcmDFuLm2fr3LBvp+il14ZnqmAie6T46ko8uYfDEKhDdR2JZUcwS8XZZrrJ1SVjoi4XZvnpCOYapVJxwjnCXgU8VyFRSejASRmeuQQkDJ3FDFF/2ktwwm8nzFi29jUJKXXgEUNSgFW+BMpmY8jrliG0oyvBAdTNRBaLrSDerKLwDXdYxavuh0Mk2gsA2Y7CGsiPljB4JHruUM5VMw9FmifMr6GmV/ZjZ/GhspNu0BbBtBx8EgK/sm2FFPrdKXtFalY8rU8uLnXiePozm0FA8Ev88PVQNO29f1MTtQAjfHBzN0RHR2BuKR+KfZfRQg845UOhuwWYEzezhgju5VQAim7uPI4kiCuZwyZU2GLHczoWoKNNhivsCC71az6vskEp1XspC5WVDhd7RYWopJd8sk0YznELazaWJYkoA7hxZSoqmrnoKh/DRU8WBUj2FQ+wEqjhQqidxeIqjRJk71bVPYfIFqmmw6qqncIji4zcvVbGoKZ/CIwiBF6riUVOu66xAtrmNnEKOpzrhV0SoOOZtprmCPgiSV6B6NFcOg+mGNmtsW6RrzVgs8tNGCi1ULuboyZo8n22epdk25NpO3TizpuSVtqHTDCdPIDjzrQ21Mpg2EHdmyFNrxT3V3vMs9rRafOpUWevB9wp4NABMYVM70V4BnSYCJV0hWf1D3bEJ/Y3jc2fxTewZa9rn6W5qSmt7GBqAdOyE6DBqFu+tW41y5gaeKXWzVgTq2TUByamqLV+0fdScfPVC17FQG28iqubRwdHLxavFYYuDNTet5bbqdEZBa6AT1suSwHPok1ziJLWd4C0u111h1xa6yrfGzfevnIRXZf7KlNW0ID5qO1qQQXnb+yOr4E4U/JaYCYgfzAhunDipNTTDqAZljV25s6FpuSCOs9za+nQwi7naRYy12GRAnTLGWQhJgRG3A+/eGlsuozx3mr/i90On3gmy6S3fG6s5gvxao/GhqxknkeNveHXu3hqp1UUVlltp8dJYpo3UCCambDkN42K20aFus3W2GHnlySxt70to3flQDcqa1HZxWmj31vi6jP9K4DePu3Rq706q25y6d2+N1PoU452rMbfeyntTWhVetcVLsw6VTy+XF0veiPcUecW4fIgL33JTris8a9bN6iV7x0j4GRiwkes2miJGryJlor7CKGaKizrBVCSMxpL8C8+goorK0J+1AKFfn2iRjcUwqum0Rv72eAyk0aqd98wMofLyaARemJog8r6+HgWBenuulcGOCntze7U8UlrXUR/MakUCtuZM+eujizKIzcSxHsZBqLwsO49qGaQR1909TZ6o4yNoBzuuKtVMr0G/rutyNvRcZzXT/A70mMeqBBYJ9KmXRgQf6P0Vy9iC0rganSuNXmYdGVMaJw2M0fsR8Napz9DHUForb41Ty9zRU2o5O/c2E7MMxmsGHj0Wz982N9CHEcvsZENx9dV5133GndaAgm8POEPzvl0vc2b41l6PkoAttbinxDB4NDpNQLSBDMOOYsNSTjtL+UUwjIYcjk6T+8C7xqCJaHd8ZySDuoQpmWFE0AOMfOhOA7OTMWlzXlXWYHVsx9MQMtk+2ND5Qu/0EqsImm6pqsBp5qpJ0joXnqoA3LTzWUZKgqgqNAmMJI+dbCAZbjFy7taFMCQ3D6g5Z2inn6cdKN7ZTX9VpUxqBHai8G11PEVdA9UmSvc2oGLHMcTLJY6qFEGlMQFQXYzyAWb3F/UCxSlq7CkIydaJbDMEUfLEG8auIwiZw8nG21k7OyWUdbjne1p9ZiApApvTqFjJKGgbGQMjh2HwpUn0ALKiACn1u4dgzJCqkiaCsmEYQXz4lp1dN0S2PncP/JkhdsudCDjLotogC4QCYNalTQT3AanB01nTgVUlTQTVuzTNDIhnrboHjAfjGGyguUrX656WnBlWU95UgGGaXa3QzP4eB7AhTwDAfGnR9FNvBSNBKFuECoD6GIEwFIaxKm0iuDCIErByBTTHVUlTQUXBP1F7KcBaVUkTQX1JYSrATKWYiXBi6IVbAU3HTs5UQAk+1NoDqFsWUHB1aRPBLbG4S0HYasIm2y2CwBPWFTTETYSHk3WmoyqkTAWDRywCSnAnR+qkbD2FOm8hR8T0NUmX0LsE/kbMjXtbCELzuHO2YdCoBS0jR2XsBEq/6aXDPh9PT0fbpibq5ObSPL08/iDyYnhsMQH2RiyNAp5RyBx3gVAnTNICj69w3VhLweMAz3Xd5dSlmHKQOrq4qxJGTx1RI7zRUOpSRsPpzegbhMGW2tejPovBRusvXx8/k0d10qOBNMSMT3dD/fMExyhfHw8g65HHIyjflz2lTBKhpszscecWtRpsl4/FbzPybpFrRAmaMxziz2hrNUTBqje1bcgWRYpZXdjEeLUU54VB0L12wo2uFCelvOae6m/dudjIycj9nGTD4BlV3GhEKSQfunh3J/5kDdwY0mZ5lwf91yDZltYXvju0cWWNChC9dzHiKEwjXJ6VGtl1xLmX55cT5+mQZ9kvZRuhN2id8OGcscpuJxXQeg5x1slSRUmmPqqz0DZBqFXNrUKMAq+oH5ohzNwNSdYNWGG6EEZOuEV9hmsWHylCWj+5TCdr5a0GPrJSJ1hFiRUtiuUG1rNpT/TxvN7AwIqewiTQGVr2T3E8kZZI107kPYIImmm4iYA+EUvdlBvL08l+uNpsgasTpOrl5TpiMrwvSaIluOx+Di2hge1qd4+rlgjz+omX9nXC19YJ0/mESgYYlXPSVOpvOQtKy4J7ihPoufArVNbScg1IBw7wGCuhuTl4miRqd+pYUeV+L04BrGvdwsRSU5GiwbauE441actmA1GiSHb/VFE9rSdZFT0rU0V3M6DLTxfm8uKHw7+Z559Pfvx0bl5c//UVmfv8CtwUP3HIL+ry9K4Qd728Obk0P5yf3N7dnI+TdHn1V/Pm6tI8ub4wb6/MD59Oln8eifDu+vrq5tY8vf50t8R/xom5/emTeXl+eXXzd+r97CPzw835Oa7B5p/PT64z/jyC7z5dm7cXl+c35vLvy9uL059yS46D+vPFhwvz4vPFLbLi2bm5vD0RUbanV5eXV5+zkiCCxQj9/OHio3lzcnZxZf54dXJzZv54sjw3/3p+I0k8knwkxNX/dnt+8/nkk/npDLnn1U1R6OMk5+A+n1zSZv0/X9Ig+b/Li5//hvpE8+TCPDv/q/nTxW32Obf8m/O/tog/OTjkk/fpw9K8/fPN+cnZ8uTDiAr+6eeLa/PPV8vbc0T5/Pbnq5ufsJee/sRB6Pbu7ydX1+efzR+XS3N5/vHy/PMtcvpJxXDx80dk5svDw8PLj7c/nvASez3Nr17/eCCwDc7qKa5MZ8hXz0/vbi+uPk+Vn8smLRNzSVGvfrq4vUX/nH8+uzj5zCqkvYgnGAd3Tw3TsMkzd209+v/PF8tz1Mh8Pj+9HWfbi6MlooSc//Pped5cjW5DUFXCrfT11efMUKef7s7Oz9iJIRSo70Evfrr4TDdD+IQ7x0IfOL5LTmseY/ssKji5Xr46PjhGbvGXP0+Rc31zvkQ0uf3w5vwvdxfoXUTz9oN5/ekTq4TTT1eoX0YxydnNBepEeAGgLh558UQhJYusOcd9PPOrhc9TBXvw7cC6YzYBkbG8+H91Gcdr6+CAQwwqzlMcmZyiNmqJgpXTE1wDzbOL5QlX09JSsy+uL+9w0LjkNuny6jQPaxj94eZUQEGemacnp38+L+M9ttc/Xp9dnozX/pcliqrHY0cvX959ukXW/3TyV2bMWXw73WKkqyQtOIq925rM75mr5CQjfsR2KNRzvDLCdCV3IgCh5n7x4uh05HvsFSmLgEaGFFccFbZa7VErfn7z4eSU3Q1PUAx9fo0KAP9dHdSMCPd4XXfJV3pLXgcjCu7QoOQvdydnu1iA53VRwUg5pOVvEkf4KdZ2d3LD35rcLdFbPCoLTbivuOPorIi2608nt2isOHp8Qpzo78ub29NdazWyfDL/5yoh0/z5/OQnSqNpgiSJnFWaQNP83e8eIXj4/e9Z5aHga3zze4sG4BMGBSaZJBkfLQ8N2X+8OTs+ODg6ETxQf80nL8vB+HyHorazn/Ihu4lCUNRCLG+vbk4+npvXV6QJpWfFjjgA72yIwriTT1cfR/TsWTRYCipHWD+d33w+/0RBK9NWi1MRxio5vbqhC84iR+eOFUfqU16dKkKrJ8BQol1nFYHo6QOVmrqx6nO4rY/5QfwUszzIJM1jeShObOsPf6g9mQSBexXmlsG/XJBE2vLTRWotisN8iVUC8nHPUwv8hOf8i9xEQBnShqu0nk3Eoh//Zm3JGXJ9AMrHFlaY1t0igd/2veM5lK9rytfh1+P9OJxFtRuAxAQrh/bfYJ2sx+gnWdQDpZ49k/+ztCInTCjl/4V3XOO1P5AmwQb6RvYkXk80wzgCnrkMTheuLd8t8eGU+EMzhuTfmMKZpY7LxmCDBAjVz1FEPvAD0zJR06CCeeA5iblG5Y2KPSCZFwpAIAPAbxYMVRU/0h8liTNzwRc7JC5BSDqE+Xlb+H4N3waRTTfLh29m0P3tW4f2P/yhMf6ToP8RRL7jb+IFcF0Fpi/Vw29JBFQCCKENfDwFTXWOLftzpBZCBE0YRUEUq4BBAiCT5N3UAqM1SN2ECYAHHiC5xhJE3gKf5Z8dKFtH0PFYIzTa99An7/kCpIkQkm3qrWog8s/kK69HZ/se+uR9HqPt24evZgHRGqchKPjzffT5e46YraFk1/QN4tk92tVG76NRw3vWhrpHfhhygAnD7mY7A8TcdguG1NaD76/9YD/7VAmgjpCGwKp+N58vFc2tWe/z9n8mn8xrJrloRtml2Rnv/5x/psg20hDx2Kdz5mD/im3eQKBlZGLhsUn3kHF/jb/b3303r4FmA8Zjrf5B/v66+F6Z1WYHyFX/+gfp+2v8wD55YL98YOZqOT9ErtraEeHvz95+iUbSPuHQ8Vj3fKCIacCJ2MhEWGMabB/F/9CK3+NvF+THObAUczNm9rvpgZBG9bdc3v2L/UsQvv+v313d3V7f3ZpnFze/N/7rd9c3V/9zfnqLV7B+vyAvT/GyBmonbjsunYj95MRJKZqOqBDWn8kgm0Yz/DIKWFM/jaG9HwJcg5OMOP6cyHsPogg87a+C1Ldj+pvsOssg3E8i1IKCXDR5ALGI0Xf7awe69j5ZBwKu8y8YxZz40FDx8NU+Tt4HyXsHQjiCX4Z2dw70vg0tF5Ftaet5jU3ZQ4yGvsmBwZfx+MNNAs63hqqhsfNpDk/fBnHym6v/5uqSXF2o0yIXXWRb9xaODdGP3x9lrmsni+ykA3uVOq5NFv4WGz9dVLr+FYhh3bcrAmtPZw8tsPMvgmQLI3yU3m/V4LdqoFGLP/h+6zF1fSjz0/H3Xehvku37g5krK56546mu1ed/q7C/VdjfKqyQkHBgwMYdD6boFzNELp6sTbKQw+sq7nf7+/i4h/fZdZkzFCRRubG65pomhtrPwbDyI7N8oM8Ul+Fniybetdcu2LQdLPsr9EH0Jl6J2I8evyFn3Hj4iIj5e2WOosqfLgrrt6IaXVTZ2QikmPJUwbrts9NMzCCk12Fi53Hzw+Fr7/Dw0Nskq5ELVfg+cG8lZELgG/qlFLf/6CTbfTJrq2N7wyvOciIrRSEKilmgb0PfehqXSqQPIx91U3ZjFpg9EWhKEyOAxq654iiad0ZexchvL9796ZuHo9P8CnX08OEi27+OpAQ2CsjRR3e3H/bf3O/9KRNQVNEyqTy1Fl5gp6hGxTBJ8bIDSWVawiQhCVdJ+gQCBMx8CtLItLYgMVcBiQ+IIiQvhFHytLTQv++zm55IE2DIg3hKDg66zh67Rm7wY2bbkUirrhIiaaSklgkM/4jMTf0+UxEIYyaxDFIrRynE7PWT5PNFprbmu/7oInZJ5lPSfe587ezxhRVZZrYrB/9IUOIyRv5eVrf7tnPJW/ragbPPaWfZ+25veXF5/eni9OL27+by9g6fiHJ9c3V9fnN7cb7ce7v3b6Sq1Zz3e2/v0bf3qNcEXyHyxsB6+CuIHHzEUow/fov/wg/g/1B7FDroKfvhU1CM07Mv3hY/xI4Xuo7lJE9mbD+YRwdHLxevFofF198VP+DTna7CtvdrnXf++S/ZX0jA3lmRFPnMoP+CyilDgbOtY1Qs/0DlUroDkoTd4bvSlclJUZhk5lP4aKlN6AQmOR0Yn+mPHg0iZ+P4wC2fJZ/mFRJ9cPgdeT1BwRj67ejw4PXxq6NXr3/5jlczOSsuX5ENHb/w8zEoDn9AKI5fvXr9khVGsTa8q5NGo7Lxw3j9+vDl8fcHrw54YSBzOEex6fg4D9HKbqnkV//9D8cHLw+/f8VtBVwasTNVPXKDlwcvvz96NVJ9dsreFD/YP/z+zcvDV4cvX3Nj6EwSGAHizfdvDl6/fnX4Ay+Im9tz87Q8uHBcKRwef3/0/dHL129GlEJ5aKKJGjTgBqNL4YeDl69/eHN4OAJDdtHTFvi2m10iyK3/+1ffHx4fvXpzNFn7mEZg//AH1CAeHhy+5maP/izyIMRBHc4o13vz+vWbH74//OV/9375/zplbdQ==END_SIMPLICITY_STUDIO_METADATA
